### ISSUE TITLE
Feature Request: Navigating to Declaration or Type Declaration of a Symbol

### ISSUE THREAD

**Issue by codeversed** [buunguyen/octotree#132]
1. Hold **[cmd]** while hovering over desired symbol in the code.
2. While holding command, **[left mouse click]** to open a Declaration or Type Declaration of a Symbol.  

Option to open in same window or new tab.

**Comment by buunguyen** [comment]
Probably a more suitable job for another extension, like https://github.com/github-linker/chrome-extension/ by @stefanbuck
