### ISSUE TITLE
Add search functionality

### ISSUE THREAD

**Issue by MHM5000** [buunguyen/octotree#137]
I think there could be an improvement to this handy extension...
A search!

Thoughts?

**Comment by mdibaiee** [comment]
Hey @buunguyen I'd like to work on this, I took a look at the code and I'm wondering about something:

There are two ways we could provide search:

1. Cache the results of `adapter.fetchData` and re-use it everytime
2. Everytime a search is requested, call `adapter.fetchData` again

Each has pros and cons, the first option might become a memory hog on big repositories, on the other hand, the second one is bandwidth consuming, what you do you say?

**Comment by buunguyen** [comment]
@mdibaiee or maybe we can use jstree search's plugin (https://www.jstree.com/plugins/)?

**Comment by mdibaiee** [comment]
@buunguyen: I didn't know about that, looks good, I'm going to work on it.

**Comment by buunguyen** [comment]
@mdibaiee :+1: guess the challenge is making the UI looks pretty while adding the feature

**Comment by mdibaiee** [comment]
Hey @buunguyen: done, may you please take a look? 

--

I couldn't build all extensions on my computer, I tested on Firefox and it works.

**Comment by buunguyen** [comment]
@mdibaiee thanks for working on this.

I've spent some time playing with your repo and in the end I don't think I want to add this search box to Octotree. It doesn't seem to add any more value than what the `t` hotkey of GitHub does while I feel it clutters the UI. I'm going to close this issue now until anyone has an idea to improve the built-in search feature of GitHub via Octotree. 

Thanks again for your effort and I'm sorry that your code (which is really good) is not merged.
