### ISSUE TITLE
FF Nightly 36.0a, e10s window, extension failed

### ISSUE THREAD

**Issue by pharmazone** [buunguyen/octotree#143]
Extension crashed in e10s windows.
But works fine in non-e10s ones.

FF Nightly: 36.0a1 (2014-11-23)
OctoTree: 1.3.1

**Comment by buunguyen** [comment]
Please try latest version with latest Firefox. Will reopen if the issue persists.

**Comment by gluons** [comment]
[Add-on Compatibility Reporter](https://addons.mozilla.org/en-US/firefox/addon/add-on-compatibility-reporter/) report that this addon is **not compatible with multiprocess**.

<img width="794" alt="default" src="https://cloud.githubusercontent.com/assets/4688092/21254583/d44ef1a6-c398-11e6-828e-acace7a685f4.PNG">
