### ISSUE TITLE
Octotree breaks appearance of pull request diffs

### ISSUE THREAD

**Issue by ruzz311** [buunguyen/octotree#151]
I keep getting an issue when I navigate to Pull Requests after having octotree open, specifically when I'm using split diffs.  The issue dissappears when I refresh the diff screen.  

[Video capture of bug happening](https://cl.ly/ZGdE?_ga=1.129915531.609429140.1421164867)

![PR display issue Screenshot](http://f.cl.ly/items/210r422H2B3w061I3n0B/Screen%20Shot%202015-01-13%20at%2010.06.50%20AM.png)

I've also had the display of the repo's main page have weird negative margin where the content is no longer centered, but I'm having a hard time recreating it.  It must be a very specific sequence of events.

**Comment by buunguyen** [comment]
@Ephemera can you help looking into this?

**Comment by Ephemera** [comment]
@buunguyen Ok. I will try to fix it this weekend.

**Comment by buunguyen** [comment]
@Ephemera Thank you, much appreciated!
