### ISSUE TITLE
Prevents default click event handler on other sites

### ISSUE THREAD

**Issue by ivanvoznyakovsky** [buunguyen/octotree#152]
go to http://www.vd.nl/dames/rokken
try to click any product.
In my chrome  39.0.2171.95 (64-bit) none of the link is working

**Comment by buunguyen** [comment]
I disable/remove Octotree and the links in that particular site also don't work. Why do you think this has anything to with Octotree in the first place? Octotree isn't loaded in any domain except from github.com or GHE deployment.

**Comment by ivanvoznyakovsky** [comment]
Only after disabling the plug-in all links started working.

----------------------
Best regards,
Ivan Voznyakovsky

**Comment by ivanvoznyakovsky** [comment]
I checked if links work properly in safari, ff, ie, chrome desktop and
mobile. All works as it should. When I install/enable octotree in they stop
reacting to click event.

----------------------
Best regards,
Ivan Voznyakovsky

**Comment by buunguyen** [comment]
As I said, I removed Octotree and the site also didn't work. And that makes sense because Octotree is not loaded in that site (unless you declared it as a GH Enterprise URL). You should look at other causes, e.g. possibly another extension, which is *actually* injected to that page, causes that.

**Comment by ivanvoznyakovsky** [comment]
checked again on new chrome profile.

you where right. octotree is not the reason.
sorry for false alarm and thnx for the extension.
----------------------
Best regards,
Ivan Voznyakovsky

On Jan 15, 2015 7:41 PM, "Buu Nguyen" <notifications@github.com <mailto:notifications@github.com>> wrote:
As I said, I removed Octotree and the site also didn't work. And that makes sense because Octotree is not loaded in that site (unless you declared it as a GH Enterprise URL). You should look at other causes, e.g. possibly another extension, which is actually injected to that page, causes that.
