### ISSUE TITLE
Left Margin added to container breaks ZenHub layout

### ISSUE THREAD

**Issue by Mottie** [buunguyen/octotree#155]
I reported this [issue at the ZenHub repository](https://github.com/ZenHubIO/support/issues/185), but discovered it was this Chrome extension causing the problems.

ZenHub fills the full browser window width and is centered using `auto` margins. When I resize my browser window Octotree adds a margin right to the container and shifts part of ZenHub offscreen.

[screenr](https://www.screenr.com/WluN)

![2015-01-20 18_43_12-boards zenhubio_support](https://cloud.githubusercontent.com/assets/136959/5829209/50cf1aa6-a0d4-11e4-89d5-f9956d72c127.png)

**Comment by buunguyen** [comment]
Hi, I've made a number of changes in re-layout. Can you check if it fixes this issue?

**Comment by Mottie** [comment]
I don't have gulp installed so I couldn't build the new files, but I did edit the chrome extension with the most recent changes - so I may have missed something.

The use of `padding` instead of `margin` now forces the container below the right sidebar when the octotree sidebar is open.

![2015-01-21 16_19_23-buunguyen_octotree](https://cloud.githubusercontent.com/assets/136959/5846478/710f573a-a189-11e4-9a96-a07f6c9ce042.png)

**Comment by Mottie** [comment]
I just tested the original changes in I made in #156. I then followed the video provided in #151 click-for-click and I did not have the same scrolling issue; this issue and that issue are due to the same problem of a `margin-left` not being removed when the octotree sidebar is hidden.

**Comment by buunguyen** [comment]
Hi, I created the dist package here: https://github.com/buunguyen/octotree/tree/master/dist. Please give it a try.

**Comment by Mottie** [comment]
It works perfectly :+1:, thank you!
