### ISSUE TITLE
Octotree browses master when page browses commit

### ISSUE THREAD

**Issue by Topher-the-Geek** [buunguyen/octotree#157]
When browsing a branch (or tag), Octotree follows along. For example, if I use the branches/tags dropdown on the GitHub page to choose a branch (or tag), Octotree does the right thing.

![branch](https://cloud.githubusercontent.com/assets/588423/5893138/84676eec-a48d-11e4-9385-e58978f3a92f.jpg)

However, when browsing a commit, Octotree shows master. For example, if I click "Browse Tree" when looking at a CL in the history, Octotree shows master rather than the commit. Furthermore, clicking on directories and files in Octotree switches the URL to the master branch rather than the commit hash.

![commit-hash](https://cloud.githubusercontent.com/assets/588423/5893146/bdaa5a2a-a48d-11e4-848f-296a8db312d9.jpg)

This is an awesome plugin! Small bugs aside.

**Comment by buunguyen** [comment]
Supported in 1.6 (releasing soon).
