### ISSUE TITLE
Allow keyboard navigation

### ISSUE THREAD

**Issue by groovecoder** [buunguyen/octotree#158]
Not sure if this is a feature request, or a request for better documentation/display of an existing feature. octotree should have a way to quickly and easily navigate the tree with the keyboard. (Arrow keys?)

**Comment by buunguyen** [comment]
It has been possible all along, but it doesn't work reliably because of an interference with pjax loading. I've just implemented a workaround. It should be possible to navigate the tree using arrow keys now. Will release with 1.6 soon.

**Comment by jvanbrug** [comment]
How do I focus and navigate the tree? After clicking on one item I am able to navigate with arrow keys, but how do I start navigating with only the keyboard, without any clicks?
