### ISSUE TITLE
Auto complete search by filename

### ISSUE THREAD

**Issue by anticafe** [buunguyen/octotree#159]
I notice in Github, when you're in a repo, press `T` will bring you to the search view by filename. Then, just type filename to search. [Here is an example](https://github.com/buunguyen/octotree/find/master)

Could you please implement such feature into Octotree. It might be an search box on the top of Octotree sidebar.

**Comment by buunguyen** [comment]
Duplicated https://github.com/buunguyen/octotree/issues/137
