### ISSUE TITLE
Links for PRIVATE submodules are broken

### ISSUE THREAD

**Issue by chr0n1x** [buunguyen/octotree#161]
Can't really give an example for obvious reasons :P

**Comment by buunguyen** [comment]
There's a fix for #172 in 1.6.4. I'm not sure if it also address the problem you're seeing. If not, please provide more details. I'd also appreciate a pull request, should be a quick change in https://github.com/buunguyen/octotree/blob/master/src%2Fadapter.github.js if you know what's wrong.
