### ISSUE TITLE
Update addons.mozilla.org

### ISSUE THREAD

**Issue by nirvdrum** [buunguyen/octotree#164]
The current version of Octotree is 1.6.1, but the latest available on addons.mozilla.org is 1.5.2.  This version doesn't seem to work any longer.  If you could push the newer versions, that would be extremely helpful.

**Comment by buunguyen** [comment]
I actually submitted 1.6 to Mozilla two months ago. And it's still being under review. Previous versions also took a long time before they got published. This time it does take longer, but I'm not very surprised given my past experience with Mozilla.

Anyway, I recommend anyone using Firefox to use the [ad-hoc build](https://github.com/buunguyen/octotree/tree/master/dist). It's identical to the one submitted to Mozilla, but without the wait.

**Comment by nirvdrum** [comment]
Ahh.  Sorry for the false report then.  I thought Mozilla was supposed to get faster at approving things.  I'll use the linked XPI from now on then.  Thanks again.

**Comment by buunguyen** [comment]
1.6 was approved today! Going to close this issue, please let me know if any problem.
