### ISSUE TITLE
Crashes with latest Nightly.

### ISSUE THREAD

**Issue by laz2727** [buunguyen/octotree#166]
Title.

**Comment by buunguyen** [comment]
Which browser and version?

**Comment by laz2727** [comment]
Mozilla Firefox 41.0a1.

2015-05-27 22:24 GMT+06:00 Buu Nguyen <notifications@github.com>:

**Comment by mdibaiee** [comment]
Well, it works not on Firefox 42.0a1, at least for me, on Mac.

I think you you should not report browser incompatibility for Nightlies, Nightly is buggy and unstable, might crash for any reason. But I think it makes sense to test on Aurora or Firefox Beta.

@buunguyen I think you can close this.

**Comment by buunguyen** [comment]
@mdibaiee thanks, closing.
