### ISSUE TITLE
Enterprise GitHub links are forgotten after restart

### ISSUE THREAD

**Issue by clayreimann** [buunguyen/octotree#175]
When I restart chrome I have to re-add my Enterprise github links before I can use Octotree.

**Comment by buunguyen** [comment]
That's strange. Is there any chance this happens in incognito mode?

**Comment by clayreimann** [comment]
I don't run in incognito mode often, but I can give it a shot

**Comment by buunguyen** [comment]
Sorry I wasn't clear. I meant the problem might happen because you're in incognito mode. If that's not the case, please ignore that comment.

Do other settings also disappear or just the GHE URLS?

**Comment by clayreimann** [comment]
It wasn't in incognito mode; but it appears I wasn't clear at first.

The GHE urls are still there, it's just that Octotree doesn't load on those pages. I found that deleting the URLs, saving settings, and then re-adding the URLs will make Octotree 'remember' them.

**Comment by buunguyen** [comment]
Does this still occur with v2?

**Comment by clayreimann** [comment]
Unsure. I'm on vacation but will let you know next week

**Comment by buunguyen** [comment]
I've just uploaded v2.0.3 with a fix regarding GHE. Please verify. Going to close this issue now. If the problem persists, I'll reopen.
