### ISSUE TITLE
"Error: Private repository" on non-private repository

### ISSUE THREAD

**Issue by joedf** [buunguyen/octotree#176]
This is the only repository that I know of in which the error occurs.
https://github.com/joedf/strapdown-topbar

**Comment by schwarzmx** [comment]
I'm having the same issue with the cassandra [repo](https://github.com/apache/cassandra).

**Comment by jdreesen** [comment]
I've experienced this issue with some repositores in the last days, too. Adding an access token doesn't help.

Examples:
- https://github.com/LeaVerou/awesomplete
- https://github.com/Ocramius/a-complex-orm-faster-than-sql

**Comment by jdreesen** [comment]
I just created a new *public* repository and get the same error. This repo was created just now and has never been private: https://github.com/jdreesen/typo3-ext-gridelements

**Comment by joedf** [comment]
Weird...

**Comment by Ephemera** [comment]
Because when default branch is not `master`, it does not request correctly.

**Comment by joedf** [comment]
nice catch

**Comment by buunguyen** [comment]
Fixed in 1.6.4.

**Comment by jdreesen** [comment]
great, thx for this awesome plugin! :)
