### ISSUE TITLE
Sync the GitHub token

### ISSUE THREAD

**Issue by sn0w** [buunguyen/octotree#183]
I really love this extension, but there is one feature I'm missing: Chrome Sync

I'm using this extension on all my computers, and as one cannot re-view a generated GitHub token, that's a lot of copy-pasting if the token changes or if I reinstall something.

AFAIK, implementing this shouldn't be very hard (at least for Google Chrome).

A short example:
```
// Save token to Chrome sync
var ghToken = "AAABBBCCCDDDEEE2133";

chrome.storage.sync.set({'ghToken': ghToken}, function() {
    message('Settings saved');
});
```

see: https://developer.chrome.com/extensions/storage

**Comment by buunguyen** [comment]
I agree, it shouldn't be difficult to support. But I'm concerned about security. Would people mind having their GH access token sync'ed to any machine they happen to login?

**Comment by greensn0w** [comment]
> Would people mind having their GH access token sync'ed to any machine they happen to login?

What if we provide sync as a "opt-in" feature?
We could also prompt the user to double-check that the token has minimal capabilities when he tries to activate sync.

Btw: When implementing sync we could/should also offer to sync the settings ;)

**Comment by joedf** [comment]
Ok, so a check box then?
