### ISSUE TITLE
Allow turning off download file by clicking icon

### ISSUE THREAD

**Issue by pdeva** [buunguyen/octotree#186]
Since the latest update, whenever i click on the file icon it downloads it.
I really dont want that. Innumerous times this has resulted in me downloading a file when i was just clicking to see its contents in github.

This is very non-intuitive behavior since never does merely clicking an icon in tree item is supposed to download it to disk.
please atleast provide an option to disable it.

**Comment by buunguyen** [comment]
Sorry, but I disagree that it's unintuitive given the icon is changed to the download icon upon mouse hover. The surface area of each tree item is large, you can click anywhere else to not trigger a download.

That said, I'm open to any suggestion to better implement the download feature.

**Comment by halilim** [comment]
While not obscenely frequent, I, too, tend to hit the download icon inadvertently when quickly traversing a repo. Given that I rarely need to download a file, I'd love a harder-to-trigger implementation. 

Options

1. Place the download icon to the left of the file icon on hover (without changing the position of the file icon and the text).
2. Add a setting to disable the feature.

**Comment by buunguyen** [comment]
@halilim sounds like a good approach. I'll accept a PR if anyone can work on it.

**Comment by jamez14** [comment]
For anyone who wants to work on this, I did some work for disabling downloading altogether. But the implementation mentioned above is different than mine in #203

**Comment by buunguyen** [comment]
This is a non-issue to me. If somebody wants it badly enough, please submit a PR.

**Comment by jamez14** [comment]
@buunguyen what would your ideal spec be for the feature? What would it include (and not include)? I'd like to know just so if I work on this feature that I don't go against any of your plans/thoughts for this repo.

**Comment by buunguyen** [comment]
@jamez14 sorry I thought I replied to this. I think an option should work (enabled by default).
