### ISSUE TITLE
Branches with "long" names are no longer working

### ISSUE THREAD

**Issue by jcready** [buunguyen/octotree#189]
`$(GH_BRANCH_SEL).children('.js-select-button').text()` now getting truncated when the branch name is "long" which means octotree isn't working because it thinks the branch name is the truncated text displayed to the user instead of the actual full branch name.

Here's the offending line: https://github.com/buunguyen/octotree/blob/master/src/adapter.github.js#L112

**Comment by jcready** [comment]
You can see an example of it now working here: https://github.com/squaremo/amqp.node/blob/confirm_promise_return/examples/confirmChannel.js

**Comment by buunguyen** [comment]
Thanks for reporting. Looks like GitHub has changed their DOM thus the primary check failed while the fallback doesn't work with long names. This has happened a few times. I'll try to find a more reliable way to implement branch-inferring mechanism.

**Comment by jcready** [comment]
I believe you could fix it as easily as changing that line to be:

```js
$(GH_BRANCH_SEL).children('.js-select-button').attr('title') ||
```

**Comment by buunguyen** [comment]
Thanks. There are actually several places in the DOM that can be used. I'm not sure what is the one that is least likely to be changed later. Also, the selector should work in all pages, not just code page.
