### ISSUE TITLE
Review all options and have sane defaults

### ISSUE THREAD

**Issue by buunguyen** [buunguyen/octotree#193]

**Comment by synapsos** [comment]
The default hotkey `Control+Shift+s` is not ideal for Firefox users as it opens the Debugger. I suggest `Control+Shift+o` for 'Octotree'. `o` is also the GitHub shortcut for 'Open', so it sort of fits.

**Comment by buunguyen** [comment]
@synapsos thanks, good to know. I'll take this into consideration when implementing this task.

**Comment by buunguyen** [comment]
Available in v2 branch and [prebuilt packages](https://github.com/buunguyen/octotree/tree/v2/dist). Will release v2 to stores next week.
