### ISSUE TITLE
Update prebuilt package for Safari

### ISSUE THREAD

**Issue by onlimii** [buunguyen/octotree#194]
The safari binary is out dated, the branch switching is not working, can only show master.

**Comment by buunguyen** [comment]
Yeah it is. Unfortunately, Apple has made a change that requires developers to subscribe to an annual paid Safari dev license, which I won't do (why should anyone pay Apple yearly to build a free extension for a little used browser.). Unless Apple revokes this policy, Safari binary will remain out of date. 

I'll make a note to the README.

**Comment by cmluciano** [comment]
Would you accept donations?

**Comment by kartikthapar** [comment]
I understand the frustration. I myself lost my mind reading the article reference in the README. As @cmluciano mentioned, would you accept donations? We can roll up a page and help fund the subscription for the current year (and then moving on...) either partly or wholly! Something to consider! :)

**Comment by buunguyen** [comment]
I wouldn't accept donation. But I'll see if there's a way to make it work.

**Comment by buunguyen** [comment]
The safari build for Octotree v2 is now available in dist.

**Comment by fossilet** [comment]
Thank you @buunguyen.
