### ISSUE TITLE
[bug] repository name and branch disappears when scrolling to bottom of octotree sidebar

### ISSUE THREAD

**Issue by duylam** [buunguyen/octotree#208]
OS: MAC 10.10
Browser: Chrome 46

Steps to reproduce

- Install unpacked chrome extension from ./tmp/chrome (after "gulp build")
- Open page https://github.com/webpack/webpack
- Collapse the "lib" folder
- Scroll down to the bottom

Expected: repository name and branch still remain
Actual: repository name and branch disappear. See below screenshot

<img width="548" alt="screen shot 2015-11-17 at 00 25 33" src="https://cloud.githubusercontent.com/assets/432049/11189265/d3e11758-8cc1-11e5-9fc4-09c32b12d357.png">

**Comment by crashbell** [comment]
Have you tried with v2 branch? It's gone with that branch.

**Comment by buunguyen** [comment]
Yes, this was fixed in v2.
