### ISSUE TITLE
Support GitLab

### ISSUE THREAD

**Issue by Chris2011** [buunguyen/octotree#21]
For my projects, I installed gitlab and for this, your addon doesn't work. It would be great, if you can add support for gitlab.

Regards

Chris

**Comment by sagitta** [comment]
:+1:

**Comment by neomede** [comment]
:+1:

**Comment by ctokoro** [comment]
:+1:

**Comment by hutusi** [comment]
:+1:

**Comment by skynet** [comment]
:+1:

**Comment by wormerr** [comment]
:+1:

**Comment by magicdawn** [comment]
:+1:

**Comment by jdreesen** [comment]
:+1:

**Comment by dalang** [comment]
:+1:

**Comment by dummer** [comment]
:+1:

**Comment by kholodilov** [comment]
:+1:

**Comment by sandish2222** [comment]
:+1:

**Comment by JorgeCastilloPrz** [comment]
:+1:

**Comment by FagnerMartinsBrack** [comment]
:+1:

**Comment by CawaKharkov** [comment]
:+1:

**Comment by ivaaaan** [comment]
:+1:

**Comment by nightink** [comment]
:+1:

**Comment by rghv** [comment]
:+1:

**Comment by natuan241** [comment]
:+1:

**Comment by glomadrian** [comment]
:+1:

**Comment by wolftune** [comment]
:+1:

**Comment by MHM5000** [comment]
It's really easy to add thumbs-up.
maybe someone should really get on this?

**Comment by buunguyen** [comment]
@crashbell has started working on this. Will take a bit of effort because GitLab doesn't provide certain equivalent API as GitHub, so we have to modify part of the core and adapter API before working on the GitLab adapter.

**Comment by FrankFan** [comment]
hello everybody,

I'm glad to announce that there is a `gitlab-tree` works the same way as the `octotree`, to display Gitlab code in tree format.

The repo is here: [https://github.com/FrankFan/gitlab-tree](https://github.com/FrankFan/gitlab-tree)

welcome try to use and give me some useful adivce, or join this repo together and make it better.

![](https://raw.githubusercontent.com/FrankFan/gitlab-tree/master/docs/gitlab-tree.png)

**Comment by buunguyen** [comment]
@FrankFan nice.

@crashbell and I are working on a version ourselves. If you like to join us, you're more than welcome. Our version will share most of the Octotree code, therefore it will share all features of Octotree and future improvements.

**Comment by buunguyen** [comment]
GitLab is supported in v2 branch. You can try out today using the [prebuilt packages](https://github.com/buunguyen/octotree/tree/v2/dist). I will release v2 to stores some time next week. Please give it a try and feel free to submit bug.

__Important__: due to some technical limitation, you must login to GitLab before Octotree can show.

**Comment by buunguyen** [comment]
Just so that everyone aware, I've released v2 that supports GitLab. It's available on Chrome and Opera now. The version for Firefox is pending review.
