### ISSUE TITLE
[bug] Sidebar is empty if browser tab opens "non-code" url

### ISSUE THREAD

**Issue by duylam** [buunguyen/octotree#213]
Browser: Chrome (not happen in Opera, unknown on Firefox as cfx tool is unavailable)

STP

- *All options in Setting page are checked*
- Open new browser tab, navigate to "non-code" page e.g https://github.com/buunguyen/octotree/pulse or https://github.com/buunguyen/octotree/pulls

Expectation: sidebar appears with source code tree structure
Actual: it's empty , see below screenshot

<img width="715" alt="screen shot 2015-11-19 at 23 39 22" src="https://cloud.githubusercontent.com/assets/432049/11276961/d976c332-8f16-11e5-868c-2dd5ec5e0fec.png">

**Comment by buunguyen** [comment]
Duplicated https://github.com/buunguyen/octotree/issues/210
