### ISSUE TITLE
Sidebar links non-ajax on Firefox

### ISSUE THREAD

**Issue by RobertAudi** [buunguyen/octotree#216]
On Firefox, the links in Octotree's sidebar open files with a regular page load. Because of this, every time a file is opened, the sidebar closes (except if the option to remember the state is turned on).

This doesn't happen in chrome.

**Edit:** There is a Bugzilla issue that might be related: https://bugzilla.mozilla.org/show_bug.cgi?id=712329

**Comment by buunguyen** [comment]
Which OS you're using? Are you using the version of Octotree in Firefox store?

**Comment by RobertAudi** [comment]
@buunguyen sorry for the late answer. For some reason, the issue resolved itself automagically. I think it might have been a bug in Github's UI which has since been fixed by the staff. At least that's the only explanation that I can come up with.

As for the Bugzilla issue, I think it's unrelated after all..

Anyway, problem solved.
