### ISSUE TITLE
Perhaps remove margin-left from html element with new github redesign

### ISSUE THREAD

**Issue by Darkle** [buunguyen/octotree#219]
With the [new design for repositories](https://github.com/blog/2085-a-new-look-for-repositories), the page is a bit more responsive, so it might make sense to only give the html element a left margin if the browser is >= about 1200px (under that and things start to move off the page), otherwise it pushes the page to the right when it doesn't need to.

(thanks for the extension btw, I use it almost every day 👍)

**Comment by crashbell** [comment]
@Darkle the problem seems fixed in version 2. You may want to take a look on it [here](https://github.com/buunguyen/octotree/tree/v2/dist).

**Comment by Darkle** [comment]
Ah ok, thanks. Will that be uploaded to the chrome extension store?

**Comment by crashbell** [comment]
I think it will :smile:

**Comment by joedf** [comment]
Soon. Not sure, he must be held back or something. :monkey:

Mentioned here:
https://github.com/buunguyen/octotree/issues/210#issuecomment-159732037

**Comment by buunguyen** [comment]
Sorry, there's one final task I need to do before releasing v2. Should be within this week.
