### ISSUE TITLE
Support BitBucket

### ISSUE THREAD

**Issue by olimortimer** [buunguyen/octotree#22]
Love the extension!

It would be great if it also displayed a tree for Bitbucket repos :)

**Comment by maximkott** [comment]
+1

**Comment by bimp** [comment]
+1

**Comment by chodorowicz** [comment]
+1

**Comment by leomperes** [comment]
+1

**Comment by drkn** [comment]
+1

**Comment by an-k** [comment]
+1

**Comment by kxxoling** [comment]
+1

**Comment by buunguyen** [comment]
I've just released Octotree 2.0 to Chrome store. This version supports GitLab using the same codebase. Hope the implementation of the GitLab adapter will inspire someone to implement an adapter for Bitbucket as I can't afford the time to do that myself. I will provide as much help as I can should anyone take on this work.

**Comment by tkothe** [comment]
+1 for Bitbucket/Stash Support

**Comment by jaxiinofea** [comment]
+1

**Comment by buunguyen** [comment]
There's a WIP for BitBucket support here https://github.com/buunguyen/octotree/pull/328. Unfortunately, the original author @itiut hasn't responded to my requests for improvements. The PR looks pretty solid though and is pretty close to being complete. Anyone here wants to continue building upon this work?

**Comment by mattblang** [comment]
@buunguyen I will try to take a look sometime over the holidays!

**Comment by ans-4175** [comment]
any news again @mattblang @buunguyen or @itiut ?

**Comment by tvytlx** [comment]
Recently, [Bitbucket Cloud gets a new navigation experience](https://blog.bitbucket.org/2017/04/11/bitbucket-cloud-gets-a-new-navigation-experience/), but it's still in beta.

To keep Octotree up to date, maybe we need to wait for a formal release of Bitbucket's UI before advancing this PR #328. (Actually, this PR works great in Bitbucket's old UI, why nobody finishes it...)

**Comment by tvytlx** [comment]
Anyway, I finish it #407.

Maybe just waiting for a new release.

**Comment by kasperite** [comment]
Hiya, any ETA for new release @buunguyen?

**Comment by buunguyen** [comment]
Will release today.

**Comment by minhkiller** [comment]
@buunguyen It is good to see you support bitbucket buddy.
I am finding some issues with the new Bitbucket UI

![image](https://user-images.githubusercontent.com/919899/29645620-1b46cb80-88c2-11e7-9719-875c90c35b65.png)

There are some big blank spaces between the octotree and the real source file. Is it able to remove the left navigation and the blank space? It will be very good one and prettier?

Remove the whole "div" like in this screenshot will make it prettier

![image](https://user-images.githubusercontent.com/919899/29645662-5855663a-88c2-11e7-9973-6ec747d57824.png)

**Comment by jarekb84** [comment]
any plans for atlassian stash support?

**Comment by chaostools** [comment]
I am assuming octotree supports  bitbucket now . can you please add set up steps in the readme for this? I am unable to setup or explore my private repos in it  :(
