### ISSUE TITLE
Not working with Firefox 43

### ISSUE THREAD

**Issue by mikhoul** [buunguyen/octotree#220]
Sadly no longer work for me, I use Firefox 43 under Windows.

If you need more informations just ask me !

Regards :grinning:

**Comment by buunguyen** [comment]
Looks like the [addon signing requirement](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox) kicks in since 43. I'll see if I can self-sign for the self-host package. In the mean time probably just wait for Octotree to appear on Mozilla store.

**Comment by mikhoul** [comment]
Thanks for the quick reply,

If you have a link to the XPI file I really don't care signed or not since I disable it and for FF44 I will use the "unbranded" version cause you will be able to disable the "sign check".

Regards :grinning:

**Comment by buunguyen** [comment]
You can find the XPI of Octotree.v2 here: https://github.com/buunguyen/octotree/tree/master/dist.

Also just read more into the doc, Mozilla only allow self-sign for addon that is unlisted on their store. Since Octotree is listed, it can't be self-signed. So looks like either have to wait for Octotree to appear on the store or disable self check to use the prepackaged XPI.

BTW, how to disable sign check in Firefox? Maybe useful to others who stumble upon this issue.

**Comment by mikhoul** [comment]
Just type "about:config" in the URL bar and change **xpinstall.signatures.required** to **FALSE**
![http://i.imgur.com/sei7dKa.png](http://i.imgur.com/sei7dKa.png)

Beginning with Firefox 44 Mozilla will release an _Unbranded version of Firefox_ (With no logo) and you will be able to disable the "sign check" inside or there will be no sign check at all in this version.

Regards :smile:

**Comment by mikhoul** [comment]
@buunguyen  There is a problem the files are corrupted, I tried with the XPI files and to be sure I tried also to download the zip file and I can't open both file in Winrar/7Zip and Firefox say the XPI file is corrupted.

Take a look on your side and let me know I will retry after ! 

Have a good day ! :tropical_drink:

**Comment by buunguyen** [comment]
Hmm, I can run the XPI in dist without problem. Disabling sign check per your instructions makes it fly. Not sure what's wrong. Are you using OSX or Windows?

**Comment by omid** [comment]
FYI, It's OK on Firefox 43 on Linux

**Comment by mikhoul** [comment]
Tried again and it work fine... maybe it was a transmission error from the server ? Who know ! :blush:

Have a nice day :christmas_tree:

**Comment by buunguyen** [comment]
Ok, good to know. I've updated README about sign-check. Closing this issue now.

**Comment by scholtzm** [comment]
I'll just add that the workaround mentioned above [no longer works in stable version](http://stackoverflow.com/a/31952728/7494817). All Firefox addons need to be signed and installed from [AMO](https://addons.mozilla.org/).

/cc @buunguyen
