### ISSUE TITLE
Add a filter field

### ISSUE THREAD

**Issue by omid** [buunguyen/octotree#221]
Amazing extension, thanks.

It would be nice if you add a filter field on top of the bar to search on file and folder names.

Thanks.

**Comment by psjay** [comment]
+1

**Comment by buunguyen** [comment]
GitHub has the `t` shortcut for that.

There's used to be a [PR](https://github.com/mdibaiee/octotree/commit/68db73a8a665574c2071f3fa94b3b5a345d664f5) to add search input to Octotree but I didn't like the look, a bit too cluttering. Will consider a PR if it keeps the UI clean.
