### ISSUE TITLE
Octotree does not ask for my GitHub personal access token in my Safari？

### ISSUE THREAD

**Issue by axiaoxin** [buunguyen/octotree#222]
I download the plugin in dir dist and installed it, but nothing happened, dose this need to do some other settings?

thanks.

**Comment by buunguyen** [comment]
I need more info, e.g. safari version, OSX, and repo you're at, any error log etc. etc.

**Comment by axiaoxin** [comment]
Safari 8.0.4 (10600.4.10.7) 

OSX 10.10.2 (14C109)

On master branch

**Comment by buunguyen** [comment]
Is there any error log in the console?

**Comment by axiaoxin** [comment]
I installed the safari extension in dist directory at master branch, where is the console? 
I install it by downloading and double click it, is something error? 

thanks
