### ISSUE TITLE
Keep the tree open when clicking the "edit file" button

### ISSUE THREAD

**Issue by dajester2013** [buunguyen/octotree#223]
Right now, when you click the "Edit File" button, the tree collapses and resets due to the page refresh.  It should stay open and highlight the current file that is being edited.

**Comment by crashbell** [comment]
There is `Remember sidebar visibility` option in Settings area. You can check this option to keep the sidebar open.

**Comment by buunguyen** [comment]
As @crashbell said.

**Comment by buunguyen** [comment]
I read it too fast.  The option in question should be "Show in non-code pages."
