### ISSUE TITLE
Error installing extension in safari

### ISSUE THREAD

**Issue by cmluciano** [buunguyen/octotree#224]
I keep getting this error when trying to drag the safari extension to install 
![image](https://cloud.githubusercontent.com/assets/4790487/11937179/a7c8a700-a7e0-11e5-9197-bebc7fd34f85.png)

Errors from Console: 
![image](https://cloud.githubusercontent.com/assets/4790487/11937188/c000cc76-a7e0-11e5-8f44-2f79c9d8d5f8.png)
https://gist.github.com/cmluciano/9bc3751138bf2c8ff16c

![image](https://cloud.githubusercontent.com/assets/4790487/11937196/cc5552f8-a7e0-11e5-8db9-2a678840eb57.png)
https://gist.github.com/cmluciano/0b893e2da05db1518c67
.

**Comment by buunguyen** [comment]
I don't have the issue on Safari 9 OSX 10.10. Not sure if this only happens on Safari 8.

**Comment by buunguyen** [comment]
I've updated installation instructions for Safari. If the problem persists, please report version number.
