### ISSUE TITLE
GitHub Enterprise 2.4 TypeError $(...).fire not a function

### ISSUE THREAD

**Issue by jarlefosen** [buunguyen/octotree#227]
With Octotree enabled on our GitHub Enterprise 2.4 website, this error keeps showing up in Chrome.
It does not happen on first load, but after a link click inside the website.
Navigating like this`https://github.my.company -> https://github.my.company/jarlefosen` recreates the problem every time on my machine.

```
Uncaught NotSupportedError: Failed to execute 'registerElement' on 'Document':
Registration failed for type 'include-fragment'.
A type with that name is already registered.
(anonymous function) @ frameworks-f8473dece7242da6a20d52313634881b3975c52cebaa1e6c38157c0f26185691.js:7
(anonymous function) @ frameworks-f8473dece7242da6a20d52313634881b3975c52cebaa1e6c38157c0f26185691.js:7

Uncaught TypeError: $(...).fire is not a function
```

This makes links unresponsive to clicks, except that it rethrows the same exception again.

```
Uncaught TypeError: $(...).fire is not a function  @ [reference to minified js]
```

**Setup**
Chrome 47.0.2526.106 (64-bit)
Octotree 2.0.1

*Disabling Octotree and the error does not appear.*

**Difference in page functionality?**
Could it be that Github Enterprise uses some kind of webapp with partials instead of loading the entire page on every location change?

**Comment by buunguyen** [comment]
I've uploaded v2.0.3 to Chrome store. This release includes a fix by @Ephemera. Please give it a try and let us know if it's fixed. Thanks!

**Comment by jarlefosen** [comment]
Sweet! The bug seems to be gone now.

Thank you @Ephemera and @buunguyen :smile:
