### ISSUE TITLE
Can't show entire source of a large repo

### ISSUE THREAD

**Issue by choldrim** [buunguyen/octotree#230]
https://github.com/WebKit/webkit
![image](https://cloud.githubusercontent.com/assets/6734555/12045633/1e4eaa8e-aee2-11e5-92e4-12895aed7081.png)

**Comment by buunguyen** [comment]
This is because the repo is too large and GitHub truncates the result. The fix is uncheck the "Load entire tree at once" option. I've just added [code](https://github.com/buunguyen/octotree/commit/f4f9ecdc52c709c09db5b1799f4efdd3bb7dc0c2) to handle and show appropriate message.
