### ISSUE TITLE
GitLab CE

### ISSUE THREAD

**Issue by jpscharf** [buunguyen/octotree#232]
1. I added my personal GitLab CE Server v8.3.2 URL to `GitHub Enterprise URLs`
2. I then added my GitLab private token to `Site access token`
3. Then tried to use Octotree on **both** a *private* and *public* repository, and it still says I do not have access to the private repository.

**Comment by buunguyen** [comment]
1. Make sure the setting is "GitLab", not "GitHub" (Enterprise URLs). You should be on gitlab.com for the setting to show.
2. Make sure you create the token on your enterprise server. Each token is specific for a site so token created on gitlab.com is different from token created on your server.
3. Do you mean you can access to public repos on your own server but not private repos?

**Comment by jpscharf** [comment]
1. My mistake, I went to gitlab.com, then I was able to add a URL for GitLab enterprise.
2. :heavy_check_mark: 
3. I was not able to access either type of repo.

Entering the GitLab Enterprise URL for my server, while on gitlab.com fixed the problem.

Is there a way to access the settings without being on gitlab or github?

**Comment by buunguyen** [comment]
Glad that the problem is fixed. You have to be on gitlab or github to change settings for now. I probably need to document this clearer in the readme.
