### ISSUE TITLE
Layout issue under gitlab compact mode

### ISSUE THREAD

**Issue by rogerz** [buunguyen/octotree#234]
<img width="435" alt="screen shot 2016-01-10 at 2 31 50 pm" src="https://cloud.githubusercontent.com/assets/43471/12220277/eb3dc22e-b7a6-11e5-9539-9ca4776433b3.png">

**Comment by buunguyen** [comment]
@crashbell can you help with this?

**Comment by crashbell** [comment]
@buunguyen sure

**Comment by crashbell** [comment]
This happens when we open GitLab in small window size, it will automatically collapse the nav bar. Let me see there's any way to resolve this issue.

**Comment by buunguyen** [comment]
Released in 2.0.4.
