### ISSUE TITLE
Doesn't work correctly for self hosted GitLab

### ISSUE THREAD

**Issue by Justineo** [buunguyen/octotree#237]
I put `http://gitlab.baidu.com` in the options panel and it worked earlier (a couple weeks ago if I remember correctly). But it doesn't work now. GitHub adapter seem to be applied rather than GitLab adapter because the API requests are sent to `api/v3/repos` which is a GitHub API endpoint.

**Comment by cedricmessiant** [comment]
I also have an issue with my self hosted gitlab. The request looks like : https://my.gitlab.com/api/v3/projects/mygroup%2fmyproject/repository/tree?path=&ref_name=master&private_token=xxxxxxxxxxxx

**Comment by buunguyen** [comment]
@Justineo sounds like you entered the GitLab enterprise URL on a github.com instead of a gitlab.com. You need to navigate to gitlab.com, then enter the URL in the text-box GitLab Enterprise URL. Let me know if that'll work.

**Comment by Justineo** [comment]
@buunguyen 

Thanks, this works. I didn't own an account on gitlab.com so I assumed github.com is the only entrance for the extension. Now I find out it's already in `README`.
