### ISSUE TITLE
Huge repository issue

### ISSUE THREAD

**Issue by Mottie** [buunguyen/octotree#240]
When Octotree finishes loading the files for a repo like https://github.com/cdnjs/cdnjs, the tree view gets truncates to only show about 140 subfolders in the `ajax/libs` folder. If you click to go to the folder in GitHub, the number of folders get truncated to 1000 folders, so I guess the difference might be the API.... 

But that wasn't my main concern, I would like to see the other root folders which somehow are not even shown:

![2016-01-19 19_24_40-cdnjs_cdnjs_ our goal is to operate this cdn in a peer reviewed fashion](https://cloud.githubusercontent.com/assets/136959/12437310/5d820768-bee2-11e5-8c85-37750dbaac61.png)

**Comment by buunguyen** [comment]
Currently, the way to work with huge repos is going to settings and unchecking "Load entry tree at once".

**Comment by Mottie** [comment]
Thanks! And oops sorry, I didn't search for the other issues related to this one first.
