### ISSUE TITLE
Issues when also using Expandinizr

### ISSUE THREAD

**Issue by gep13** [buunguyen/octotree#246]
I have just found your Chrome extension, and I have to say, it looks amazing!

I have just installed it and it seems to function exactly has expected, but with one slight annoyance...

I also make use of the Expandinizr Chrome Extension:

https://github.com/thecodejunkie/github.expandinizr

And when used in conjunction with Octotree, items get pushed off the right hand side of the screen.  As an example:

![image](https://cloud.githubusercontent.com/assets/1271146/12606930/153c2bc2-c4c9-11e5-96e4-6d10471ce0cf.png)

Is there anything that can be done to make these two extensions place nice together?  They seem like very complementary extensions, and it would be great if they could work together.

Thanks!

**Comment by gep13** [comment]
This is related to this:

https://github.com/thecodejunkie/github.expandinizr/issues/49

Hopefully you two teams can work together to get this working.

**Comment by southpawlife** [comment]
I just noticed this as well, I will take a look as time permits. It seems one option would be to make Expandinizr dynamically size based on the available horizontal screen real estate.

**Comment by buunguyen** [comment]
In 2.0.8, Octotree adds class `.octotree` in html when it's available and class `.octotree-show` when the sidebar is shown. Hopes that helps with custom user style or other extensions to play nice with Octotree.
