### ISSUE TITLE
GitLab load entire tree

### ISSUE THREAD

**Issue by stephanvl** [buunguyen/octotree#247]
In GitLab v8.4 they added the ability to find any file in the repository by fuzzy searching.

This is implemented by first downloading a JSON file with all files in the repository and then search through this array client side.

This allows us to also download the full JSON file and we then have the entire tree in one request.

The URL is as follows:
`https://<host>/<group>/<project>/files/<branch>.json`

I think it would be nice to use this url for loading all data at once. Maybe do some post processing in the `.done` callback of the request to set the name and type.

The only thing I can think of is that the type 'commit' can't really be determined without loading the submodules too. Maybe instead of first loading the tree, then the submodules, load submodules first and give the output to the function loading the tree.

**Comment by buunguyen** [comment]
I'd rather wait for GitLab to improve their API https://gitlab.com/gitlab-org/gitlab-ce/issues/4205
