### ISSUE TITLE
Icon disappeared

### ISSUE THREAD

**Issue by d6u** [buunguyen/octotree#248]
![image](https://cloud.githubusercontent.com/assets/2153667/12725983/449e9814-c8e3-11e5-9add-69fd0077f20e.png)

This started from last night, preliminary guess is the icon font stylesheet somehow disappeared.

![image](https://cloud.githubusercontent.com/assets/2153667/12726083/b120f0a4-c8e3-11e5-8757-78abc25e5292.png)

**Comment by buunguyen** [comment]
Suppose Chrome. It was fixed in 2.0.4.

**Comment by d6u** [comment]
Oh, thanks! Manually update the extension fix the issue.
