### ISSUE TITLE
Latest Version have some bugs...

### ISSUE THREAD

**Issue by mikhoul** [buunguyen/octotree#249]
<ins>**Very Slow**</ins> to load and some characters are not decoded...

http://i.imgur.com/GqkCREF.png

**Comment by Joshua-F** [comment]
Dupe of #248? If so it was fixed in 2.0.4.

**Comment by buunguyen** [comment]
If Chrome, then it's a duplicate. Firefox/Opera/Safari don't have fix yet.

**Comment by mikhoul** [comment]
On Firefox, Do you have a version compiled (XPI file) ?

**Comment by buunguyen** [comment]
Sorry, no solution for Firefox yet. https://github.com/buunguyen/octotree/issues/250
