### ISSUE TITLE
Strange characters are shown in place of icons

### ISSUE THREAD

**Issue by buunguyen** [buunguyen/octotree#250]
GitHub recently introduced a change. Basically the site doesn't load the [Octicons](https://octicons.github.com/) icon font anymore. This causes all icons in Octotree to show strange characters. I have released the fix for Chrome in 2.0.4. If you encounter the issue, please make sure the extension is up to date (or remove & add back if necessary). I will release an update for Opera shortly.

As for Firefox and Safari, there's no solution yet. The current fix requires embedding the font file with the extension and declare a `@font-face` in [github.less](https://github.com/buunguyen/octotree/blob/master/src%2Fadapters%2Fgithub.less#L3). But I haven't found a way to embed custom font for Firefox addon (haven't tried Safari). I tried to base64-encode the font and embedded it into `@font-face`'s src, but still couldn't make it work. If anyone has any suggestion or make a PR to fix, it's highly welcome.

**Comment by leoj3n** [comment]
:+1: I can confirm this fixes it.

**Comment by joedf** [comment]
That's unfortunate. I imagine you have already tried the solutions from here:
http://stackoverflow.com/a/24359746/883015
Although it might not be optimal, you could use hosted versions from cdnjs:
https://cdnjs.com/libraries/octicons
Otherwise, it might be better to just fall back to images.

**Comment by mikhoul** [comment]
I agree for the fallback on images for Firefox.

**Comment by joedf** [comment]
I got it. Let's just use SVG like GitHub is doing right now.
For example (Star Button :star: ):
```svg
<svg aria-hidden="true" class="octicon octicon-star" height="16" role="img" version="1.1" viewBox="0 0 14 16" width="14"><path d="M14 6l-4.9-0.64L7 1 4.9 5.36 0 6l3.6 3.26L2.67 14l4.33-2.33 4.33 2.33L10.4 9.26 14 6z"></path></svg>
```

**Comment by buunguyen** [comment]
Can the fix be applied strictly to the github.less only? So that it wouldn't affect GitLab. I suppose we can conditionally change templates & code, but that change will be ugly and difficult to maintain.

**Comment by crashbell** [comment]
How about using DataURI to include SVG directly in `github.less`?

**Comment by joedf** [comment]
@buunguyen
Ahhh right... I understand :(
@crashbell
That might work. Can anyone test or confirm this?

**Comment by crashbell** [comment]
@joedf I tested and it could work with some adjustment. The code would be something like: 
![Uploading Screen Shot 2016-02-03 at 11.35.44 AM.png…]()

**Comment by buunguyen** [comment]
@crashbell thanks for looking into this. Do you have time for a PR?

**Comment by crashbell** [comment]
I will work on this within this weekend. It pretty takes time to find the corresponding SVG icons.

**Comment by joedf** [comment]
@crashbell  Got the SVGs for ya, looking foward to the PR :) :+1: 
  
Unicode	|	Class name				|	SVG																							|
--------|---------------------------|-----------------------------------------------------------------------------------------------|
f02c	|	.octicon-question		|	[question.svg](https://github.com/github/octicons/blob/master/svg/question.svg)				|
f001	|	.octicon-repo			|	[repo.svg](https://github.com/github/octicons/blob/master/svg/repo.svg)						|
f020	|	.octicon-git-branch		|	[git-branch.svg](https://github.com/github/octicons/blob/master/svg/git-branch.svg)			|
f016	|	.octicon-file-directory	|	[file-directory.svg](https://github.com/github/octicons/blob/master/svg/file-directory.svg)	|
f011	|	.octicon-file-text		|	[file-text.svg](https://github.com/github/octicons/blob/master/svg/file-text.svg)			|
f00b	|	.octicon-cloud-download	|	[cloud-download.svg](https://github.com/github/octicons/blob/master/svg/cloud-download.svg)	|
f017	|	.octicon-file-submodule	|	[file-submodule.svg](https://github.com/github/octicons/blob/master/svg/file-submodule.svg)	|
f02f	|	.octicon-gear			|	[gear.svg](https://github.com/github/octicons/blob/master/svg/gear.svg)						|
f078	|	.octicon-chevron-right	|	[chevron-right.svg](https://github.com/github/octicons/blob/master/svg/chevron-right.svg)	|
f0a4	|	.octicon-chevron-left	|	[chevron-left.svg](https://github.com/github/octicons/blob/master/svg/chevron-left.svg)		|

**Comment by crashbell** [comment]
Thank you @joedf 
A PR was made here #252

**Comment by joedf** [comment]
Great! :+1:

**Comment by buunguyen** [comment]
Updated version has been submitted to the stores. Many thanks to @crashbell and @joedf for helping out with this!
