### ISSUE TITLE
Octotree won't show up if Firefox privacy setting is "Never Remember"

### ISSUE THREAD

**Issue by resilva87** [buunguyen/octotree#251]
Hi,

I have Octotree installed in my Chrome browser, working pretty fine. Had just switched to Firefox and installed Octotree plugin, but my privacy setting is most of the time set to "Never Remember", so I thought it was some kind of weird installation bug that Octotree would never show up.

It turns out that after setting it to "Remember history" Octotree is indeed showing, so I thought to make this report.

Some info:
- I'm running Linux Mint 17.2 Rafaela (3.16.0-38-generic #52~14.04.1-Ubuntu x6_64 x86_64 GNU/Linux)
- Firefox for Linux Mint 44.0

Thanks!

**Comment by resilva87** [comment]
Hi,
@Ephemera Thanks a lot!
@buunguyen any idea on when will this release be available as a Firefox plugin?

Cheers!

**Comment by buunguyen** [comment]
It's submitted already, should take couple of days.

**Comment by resilva87** [comment]
Alright, thanks a lot!
