### ISSUE TITLE
Octotree won't show up after the latest Chrome update

### ISSUE THREAD

**Issue by volkanunsal** [buunguyen/octotree#254]
The button isn't showing up on its own. I have to restart the extension for it to show.

**Comment by buunguyen** [comment]
Not sure the cause to this. But I just submitted an update v2.0.7 (with fixes not relating to this). Please let me know if the issue happens again with this version.

**Comment by volkanunsal** [comment]
@buunguyen I'm still seeing this in version v2.0.8.
