### ISSUE TITLE
GitLab: Copy from raw page copies octotree hint

### ISSUE THREAD

**Issue by Razer6** [buunguyen/octotree#261]
When copying a file content from the `raw` page on a GitLab repository copies an invisible hint from octotree is copied with it:

```
Octotree is enabled on this page. Click this button or press cmd shift s (or ctrl shift s) to show it.
```

**Comment by crashbell** [comment]
@Razer6 thank you! I have just created a PR to fix this.

**Comment by buunguyen** [comment]
What's a raw page?

**Comment by Razer6** [comment]
@buunguyen The `raw` view of a file, e.g. https://gitlab.com/gitlab-org/gitlab-ce/raw/master/.foreman

**Comment by buunguyen** [comment]
@Razer6 thanks, but I don't see Octotree show on that page. Do I miss anything?

**Comment by crashbell** [comment]
@buunguyen you can select all the text and paste it to any text editor. Or you can hover the cursor around the top left to open Octotree sidebar.

**Comment by buunguyen** [comment]
@crashbell oh right, thank you.
