### ISSUE TITLE
The tree didn't show up on Safari

### ISSUE THREAD

**Issue by yakiang** [buunguyen/octotree#264]
It's Yosemite.

![](http://i11.tietuku.com/2634f10043f93125.png)
![](http://i11.tietuku.com/9fb9a9bcb4f8d81a.png)

**Comment by buunguyen** [comment]
Which version is it?

**Comment by yakiang** [comment]
Octotree 2.0.7
Safari 8.0.6 
:)

**Comment by DrewML** [comment]
I'm guessing this is most likely due to the following in `octotree.js`:

```javascript
const views = [treeView, errorView, optsView]
for (const view of views) {
```

which Babel compiles down to a for-loop that makes use of `Symbol.iterator` (not supported in Safari). If that's the case, we could fix the issue either by pulling in the babel polyfill (core-js), *or* that loop could be changed to use Array#forEach.

@buunguyen do you have a preference?

**Comment by buunguyen** [comment]
I'd prefer the forEach to avoid increasing the size. I don't think there are many for...of in the code anyway.

**Comment by DrewML** [comment]
Looks like for-of is only used once in `octotree.js`, and once in `adapters/github.js`. Will submit a PR shortly making the switch to forEach.

**Comment by buunguyen** [comment]
@yakiang please try the latest version. Note the installation instruction has changed. Let me know if there's any issue installing.

Many thanks to @DrewML for the PR.

**Comment by yakiang** [comment]
@buunguyen Thanks a lot!
I've re-installed the extension, no more warnings or errors now, but there's still problems, as the screenshot shows.

![screenshot](http://i13.tietuku.com/288437d2ac5551e4.png)

BTW, my environment now is:
Safari 9.0.3
El Capitan 10.11.3

**Comment by buunguyen** [comment]
Do you see any error log? Also if possible, please inspect the DOM and show send me a picture of `html` and `.octotree_sidebar`.

**Comment by yakiang** [comment]
I pasted the full html here: https://gist.github.com/yakiang/2316d89fb71a25b95179
And there's not any errors or warnings : (

**Comment by buunguyen** [comment]
This looks wrong `<nav class="octotree_sidebar ui-resizable octotree_github_sidebar" style="width: 1px;">`. Not sure how the width ends up with 1px. Try set local storage `octotree.sidebar_width` to "250" and reload the page.

**Comment by yakiang** [comment]
Tried `localStorage.setItem('octotree.sidebar_width', '250')` and it works! Can navigate within the tree now. Thank you! @buunguyen
