### ISSUE TITLE
Ship as part of GitLab

### ISSUE THREAD

**Issue by dosire** [buunguyen/octotree#265]
Hi Buu,

Are you open to having us ship octotree as part of GitLab? This would help with usage:

1. Users no longer have to install anything.
2. On-premises users (the majority of GitLab users) don't have to configure it https://github.com/buunguyen/octotree#enterprise-urls
3. We might add support for recent versions of Internet Explorer

Obviously we would do all the work of integrating this and we would contribute back any fixes that are relevant.

What do you think? Please let me know if you prefer to talk about this.

**Comment by buunguyen** [comment]
@dosire I think a built-in tree view is probably best for your users. Just to be clear though, what do you mean by shipping Octotree as part of GitLab? Are you going to implement the tree from scratch or taking bits and pieces from Octotree?

**Comment by dosire** [comment]
@buunguyen I'm thinking about reusing as much of Octotree as we can and contributing back any fixes we make in its code.

**Comment by buunguyen** [comment]
Gotcha. Unless a change is non-GitLab specific, I don't think contributing back is necessary as there's no reason to keep GitLab support in Octotree if the feature is built-in. @crashbell and I myself spent many months working on and off to bring GitLab support to Octotree. It's a bit sad that we can't enjoy the fruit of our labor a bit longer ;). But I guess this is best for the community and I'm glad our work helps improve GitLab.

**Comment by dosire** [comment]
@buunguyen I agree that only generic changes would make sense to contribute back.

I'm sorry that integrating it would negate your and @crashbell's work on it. Obviously we really happy that there is support right now. And I'm not sure if and when we'll add support in GitLab itself, but I wanted your blessing before proceeding, thanks.

Can I make you both happy with some GitLab swag?

**Comment by dosire** [comment]
Link back to GitLab issue https://gitlab.com/gitlab-org/gitlab-ce/issues/13723

**Comment by buunguyen** [comment]
@crashbell may chime in here but I don't think he would object. The code is MIT anyway so it's kind of you to ask for our blessing. Please go ahead.

**Comment by dosire** [comment]
Thanks @buunguyen

**Comment by vindarel** [comment]
So, they are not shipping Octotree but they are integrating VSCode: https://gitlab.com/gitlab-org/gitlab-ce/issues/31890

Near the end of the first issue, we discover a similar project: https://github.com/git-toni/reposplit (Chrome only ATM, Gitlab support but no private Gitlab projects)

**Comment by leocaseiro** [comment]
I've just found an extension working very well for gitlab: https://chrome.google.com/webstore/detail/gitlab-code-view/gglalfcdiahpedikbmegmmkmpmajnpjj
