### ISSUE TITLE
Best way to go about creating an octotree history extension

### ISSUE THREAD

**Issue by gitsense** [buunguyen/octotree#270]
Hi,

I'm currently looking at what would be required to modify octotree, so it could be used to navigate the changes in a branch.  We have a GitSense extension (http://gitsense.github.io) which does this, but it is only accessible from the commits page.  The following screenshot shows what our Changes Tree looks like for the octotree repository:

![octotree](https://cloud.githubusercontent.com/assets/5347894/13370990/954f8804-dccf-11e5-86d8-4c9ce763d003.PNG)

Since this tree is only accessible from the commits page, it's not as convenient as we would like.  How octotree is integrated with GitHub is significantly better, hence me creating this issue.

Octotree clearly owns the left hand side of the screen and really, we wouldn't want to remove the functionality that octotree offers anyway.  What we are left with are the following two options:

1. We fork octotree and maintain our version and sync with your repo from time to time
2. We modify octotree to support our Changes Tree and merge the changes back to the main octotree repository.

Ideally we would like to go with option 2, but we'll need your approval first.  What ever changes we make, they will definitely not affect existing octotree users.

What I was thinking was, we modify the options section, so it presents something like "check this box to enable Changes Tree browsing".  And once enabled, we'll render the two different trees in their own tab.  Below is a very crude mockup of what I'm talking about:

![octotree2](https://cloud.githubusercontent.com/assets/5347894/13371308/e295c382-dcd7-11e5-9438-7d45504846c4.PNG)

It could be buttons or toggle switches.  The only real requirement would be, it has to be easy for users to switch between the two different tree types.

Let me know what you think.  

As a side note, our indexing technology works with Bitbucket, so octotree can be modified to work with Bitbucket if it uses our API.

Cheers

**Comment by joedf** [comment]
a History tab would be kind of cool :+1:

**Comment by buunguyen** [comment]
Hi,

The history looks nice. What do you think about showing both (after users check the checkbox) in the same tree? Maybe there's an icon next to each file that when hover then click will show the changes (sort of like how the Download button is implemented?

You mentioned about the indexing technology. Do you mean your code will need to integrate with some backend? Is it free (forever) or paid? I certainly wouldn't want Octotree users to be locked into a pay platform anyhow.

**Comment by gitsense** [comment]
@buunguyen I think it will be best to have a very separate view for each tree as they both serve a different purpose.  The history tree also creates more noise (it shows deleted files/folders) and the behaviour changes when you click on a file.  

As for the indexer.  Right now it's not possible to generate the history tree with GitHub's API and I don't see this being possible in the future.  To produce the information required to generate the history tree would be too cost prohibitive/challenging for GitHub given their scale.

The only way users can generate the tree would be to install our indexing engine on their own infrastructure (laptop, cloud, etc) and configure their browser to use that indexing engine.  The indexers will be free to use provided the number of commits are below 25,000 per repository for private/commerical use.  For open source repositories there is no restrictions.

**Comment by buunguyen** [comment]
In that case, I think you should probably create another extension as the functionality differs and the so is the support (Octotree supports GitHub and GitLab while you support GitHub and BitBucket). An idea is if your extension detects Octotree, it would append a tab like your design. Or maybe a new design altogether that will work regardless of whether Octotree exists or not, i.e. show the trigger button in another location.

**Comment by joedf** [comment]
What @buunguyen said :+1:
