### ISSUE TITLE
Layout error on recent version of Firefox

### ISSUE THREAD

**Issue by sunng87** [buunguyen/octotree#271]
Hi, I'm on Firefox 44 and Octotree 2.0.7. Recently I found the sidebar has become like this when I click it:

![2016-02-29-161900_1915x910_scrot](https://cloud.githubusercontent.com/assets/221942/13389111/613f0ab6-df00-11e5-8d07-30f60a0b7008.png)

And there is just no way to get back unless I refresh the page. This is weird and I'm reporting here to see if any other Firefox users have same issue with me. I have ublock installed if you ask. But the issue is still here when ublock is disabled.

**Comment by buunguyen** [comment]
Hi, does it always happen or go away after you refresh the page?

**Comment by sunng87** [comment]
It always happens to me. I reinstalled it and the issue still exists.

**Comment by buunguyen** [comment]
Please enter this to the console localStorage.getItem('octotree.sidebar_width'), what's the output?

**Comment by sunng87** [comment]
I'm getting 

```
localStorage.getItem('octotree.sidebar_width')
"2361"
```

**Comment by sunng87** [comment]
I just removed this value and it now works!

**Comment by unluisco** [comment]
@buunguyen I am having this issue too
![imagen](https://cloud.githubusercontent.com/assets/6332263/19373298/8fce6044-9188-11e6-8515-1c1ce5ab0018.png)
this is in the console:
```
localStorage.getItem('octotree.sidebar_width')
"1085"
```

**Comment by buunguyen** [comment]
localStorage.setItem('octotree.sidebar_width', 250)
