### ISSUE TITLE
[GitLab] Diff box heading shown on top of page heading on Merge Request

### ISSUE THREAD

**Issue by Razer6** [buunguyen/octotree#272]
When scrolling down, the diff box heading is shown on top of the page header. Normally it should be hidden below.

See the screenshot below

![screenshot 2016-03-01 12 34 14](https://cloud.githubusercontent.com/assets/278301/13443851/51cfa65e-e003-11e5-881c-b34bc99a4357.png)

### Reproduction Steps

1. Go to https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/3024 (or any other MR with a discussion on the diff)
1. Scroll down such that the diff discussion is fading out on the top of the page
1. Watch the diff header showing on top of the page header

**Comment by buunguyen** [comment]
Fixed in 2.0.9.

**Comment by Razer6** [comment]
Thanks for fixing it so fast!
