### ISSUE TITLE
gitlab could not use octotree

### ISSUE THREAD

**Issue by pippolover** [buunguyen/octotree#280]
i use enterprise version of gitlab.
i could not find octotree button on new version of gitlab , could u have a look at this problem?
i try on gitlab.com and i could not find the button as well.

**Comment by leocaseiro** [comment]
Hi @pippolover, you must add your gitlab url in settings from a gitlab.com repo first:

1. Go to https://gitlab.com/gitlab-org/gitlab-ce
2. Open octotree ![screen shot 2016-04-08 at 5 11 54 am](https://cloud.githubusercontent.com/assets/940070/14363599/76759d94-fd48-11e5-948b-319d8db60545.png)
3. Click at settings ![screen shot 2016-04-08 at 5 12 00 am](https://cloud.githubusercontent.com/assets/940070/14363614/8aded958-fd48-11e5-8d9d-eee7b1553093.png)
4. Than add your URL at **GitLab Enterprise URLs**
5. Click at **Save** button

After that, you're done :smile:

**Comment by pippolover** [comment]
tks so much @leocaseiro .
problem fixed.

**Comment by leocaseiro** [comment]
@buunguyen that would be nice add this step by step to `README.md`. What your thoughts?

**Comment by buunguyen** [comment]
The readme does [mention it](https://github.com/buunguyen/octotree#enterprise-urls), but it might not be clear enough. If you think an improvement can be made, feel free to submit a PR.
