### ISSUE TITLE
Safari: Missing GitLab Enterprise URLs field

### ISSUE THREAD

**Issue by leocaseiro** [buunguyen/octotree#281]
Hi, I'm trying to setup my enterprise gitlab in Safari, but the field to add an URL is missing:

### Safari Screenshot
![screen shot 2016-04-08 at 11 48 41 am](https://cloud.githubusercontent.com/assets/940070/14371968/c86f9988-fd7f-11e5-889f-54086fa3f7d2.png)

### Chrome Screenshot
<img src="https://cloud.githubusercontent.com/assets/940070/14371979/eb3943f6-fd7f-11e5-8326-af2c82285ed1.png">

Both using 2.0.9

Thanks

**Comment by buunguyen** [comment]
Currently only Chrome & Opera supports enterprise sites. Firefox and Safari don't provide a mechanism for extension to run on arbitrary domains, AFAIK. But you can modify files in the config directory and create a custom build for your enterprise domains.

**Comment by leocaseiro** [comment]
Hi @buunguyen, 

Thanks for your reply.

if I  add the URL at the manifest.json would work? I'm sorry, but there's a build process after that? Would you mind helping me out? I haven't done any safari extension before.
Thanks

**Comment by buunguyen** [comment]
You should modify config/safari/info.plist. Also modify [this line](https://github.com/buunguyen/octotree/blob/master/src%2Foctotree.js#L16) to add the enterprise URL.
