### ISSUE TITLE
Support for self-hosted GitLab

### ISSUE THREAD

**Issue by ajsb85** [buunguyen/octotree#282]
Can we add a new URL as option to use our instance of GitLab in these files: 
`background.js`
`manifest.json`

**Comment by buunguyen** [comment]
You can follow instructions here https://github.com/buunguyen/octotree#enterprise-urls

**Comment by ajsb85** [comment]
I try in different ways but I cannot see the permission prompt.
Can you make a screencast?
Thanks.

**Comment by leocaseiro** [comment]
Hi @ajsb85, make sure you are not using Safari at it doesn't work there.
Try on Chrome.

This is a [step by step](https://github.com/buunguyen/octotree/issues/280#issuecomment-207054600) that might help you
