### ISSUE TITLE
 I can't use octotree 

### ISSUE THREAD

**Issue by 15757170756** [buunguyen/octotree#284]
Hint:
Error: Forbidden
You are not allowed to access the API. You might need to provide an access token. Follow this link to create one and paste it below.

**Comment by 15757170756** [comment]
what can i do to solve the problem

**Comment by rkichenama** [comment]
Go to github and create an access token, then go to the options menu of
OctoTree and enter the token.

**Comment by Ephemera** [comment]
Generate new tokens: https://github.com/settings/tokens/new
