### ISSUE TITLE
enterprise url configuration

### ISSUE THREAD

**Issue by glensc** [buunguyen/octotree#285]
https://github.com/buunguyen/octotree#enterprise-urls

so i open some github url, like https://github.com/buunguyen/octotree

i'm unable to locate thing what you call `Open the Octotree settings panel` in Chrome/50

what i think you mean is `Options` appearing from Toolbar Button, but it appears to be gray, i.e disabled. what's up with that?

![untitled](https://cloud.githubusercontent.com/assets/199095/14831480/acab2a68-0bfe-11e6-9da4-db64bb0a0818.png)

i tried installing the extension from Chrome Web Store and also from your github repo, no differences

**Comment by buunguyen** [comment]
You can open the settings panel by clicking the gear icon in the octotree sidebar.

**Comment by glensc** [comment]
please update documentation to be clear on this topic. attach screenshot if needed?
