### ISSUE TITLE
repo size

### ISSUE THREAD

**Issue by glensc** [buunguyen/octotree#286]
i don't think you should commit the binary generated content to git repo
https://github.com/buunguyen/octotree/commit/f8e080c16aed44226edc9f26c87c294c4fa7665d

upload them up to releases page instead
https://github.com/buunguyen/octotree/releases

packed repo is already 56mb in size...

**Comment by buunguyen** [comment]
The zip of the entire repo is 3.7MB. The dist is less than 1MB. So I have no idea what that 56MB comes from. The purpose of the dist is for people to install latest prebuilt package from a trusted source.

**Comment by glensc** [comment]
i'm speaking about **git** repository, the source code clone:

    git clone https://github.com/buunguyen/octotree.git

and i'm saying that you do not store the built artifacts in git repo, but use the "releases" github feature and upload there them under appropriate tag.
