### ISSUE TITLE
Self hosted gitlab + Firefox

### ISSUE THREAD

**Issue by darinkes** [buunguyen/octotree#288]
Hi,

Just a question why there is no support for GitLab Enterprise in Firefox?

``
Support GitHub and GitLab Enterprise (Chrome and Opera only, see instructions)
``

Greetz

P.S.: The Firefox Plugin claims the Feature " Support GitHub and GitLab Enterprise".

**Comment by darinkes** [comment]
Ah! Found Issue #275 with the explanation.

The Plugin-Info for Firefox should be updated

**Comment by darinkes** [comment]
Regarding this topic: How can you build your own octotree plugin?

```
~/octotree$ jpm xpi
JPM [info] Starting jpm xpi on octotree
JPM [error] XPI creation failed: Error: The addon has no valid entry point. Either create an entry point
at `./index.js`, or set the `main` property to a valid path in
your addon.
```

**Comment by buunguyen** [comment]
gulp dist
