### ISSUE TITLE
Wish: Support for internal and external gitlab/github

### ISSUE THREAD

**Issue by darinkes** [buunguyen/octotree#289]
Hi,

I found no way to configure more than one site access token.
Now I can use the plugin in our internal gitlab, but not for gitlab.com.

Greetz

**Comment by dotMorten** [comment]
We have an on-premise GitHub Enterprise server as well. Would love to be able to use it with this in addition to github.com

**Comment by buunguyen** [comment]
Access token is per-site basis. Go to the site in question, then fill in access token, it will be stored only for that site.
