### ISSUE TITLE
Support of relative URL installations

### ISSUE THREAD

**Issue by artem-sidorenko** [buunguyen/octotree#295]
Thx for a very cool extension:)

One issue, which might be typical for enterprise installations: [relative URL support](http://docs.gitlab.com/omnibus/settings/configuration.html#configuring-a-relative-url-for-gitlab).

We have a GitLab installation with relative URL: https://example.com/gitlab

When I go to [gitlab.com repo](https://gitlab.com/gitlab-org/gitlab-ce) everything works as expected and see `gitlab-org/gitlab-ce` in octotree as repository name

When I go to our installation with relative URL, e.g. `https://example.com/gitlab/groupname/myrepository`, I see in octoreee `gitlab/groupname` as repository name and octotree fails to load the data

I use it in Chromium and installed the extension from Chrome Web Store

**Comment by crashbell** [comment]
Did you check https://github.com/buunguyen/octotree#enterprise-urls?

**Comment by artem-sidorenko** [comment]
@crashbell yes, I followed the steps: token is recognized, extension loads, but the repo is not properly recognized.

If you want, I can create a VM on digitalocean with this setup, so you can verify it live

**Comment by crashbell** [comment]
Can you please post the errors here? I'd like to give a shot to see.

**Comment by artem-sidorenko** [comment]
I didn't look for any errors yet, the basic thing that I see is this:

**gitlab.com without relative URL setup**
URL: https://gitlab.com/gitlab-org/gitlab-ce
![gitlabcom](https://cloud.githubusercontent.com/assets/1645670/15389211/0ba3f900-1db6-11e6-8d4e-fa8b5bc448d2.png)

So, it works


**on-premise setup with relative URL setup**
URL: https://example.com/gitlab/rainbow/doc-starterkit
![relative-url](https://cloud.githubusercontent.com/assets/1645670/15389240/2f240ce4-1db6-11e6-9659-1595d5745407.png)

It doesn't work and I expect it to be `rainbow/doc-starterkit` instead of `gitlab/rainbow`

**Comment by crashbell** [comment]
Can you please give me the erros in console (Chrome Dev Tools)? It might have some clues for us :)

**Comment by artem-sidorenko** [comment]
@crashbell :-)

![untitled](https://cloud.githubusercontent.com/assets/1645670/15389909/6d304086-1db9-11e6-8bae-cea2898a5280.png)

**Comment by buunguyen** [comment]
@crashbell @artem-sidorenko pretty clear that Octotree doesn't understand the relative url. Best if we can find out if there's a GitLab API call to retrieve the relative URL of the current domain. Otherwise, it may need supplying by user, an extra option.

**Comment by artem-sidorenko** [comment]
@buunguyen you already have it: https://example.com/RELATIVE_URL_HERE

**Comment by buunguyen** [comment]
@artem-sidorenko when is it a relative URL and when is it a username?

**Comment by artem-sidorenko** [comment]
@buunguyen if I follow [this](https://github.com/buunguyen/octotree#enterprise-urls) steps and I'm adding a URL in the configuration as enterprise URL for some GitHub/GitLab installation, its definitely a relative URL and not a username

**Comment by buunguyen** [comment]
You just repeat what I said.

> maybe in the GitLab Enterprise URL, require users to add the relative path if one exists.

**Comment by buunguyen** [comment]
@crashbell can you help work on this?

**Comment by artem-sidorenko** [comment]
> maybe in the GitLab Enterprise URL, require users to add the relative path if one exists.

My understanding of this is/was: to add an additional option `relative_url` which should be configured together with enterprise URL. Whats why I said you already have this configuration and information.

@buunguyen sorry for possible confusion.

**Comment by buunguyen** [comment]
np, I meant the same field.

**Comment by buunguyen** [comment]
> I can create a VM on digitalocean with this setup, so you can verify it live

It would be very helpful. If @crashbell doesn't respond, I can take care of this.

**Comment by artem-sidorenko** [comment]
@buunguyen http://159.203.112.67/gitlab and test repo http://159.203.112.67/gitlab/root/octotree

if you need an account, feel free to create one (but I guess email confirmation won't work)

**Comment by buunguyen** [comment]
Unfortunately it doesn't allow me to login without confirming email.

**Comment by artem-sidorenko** [comment]
@buunguyen I sent you the credentials via mail

**Comment by crashbell** [comment]
I'm working on this, the root cause was addressed (`/gitlab` breaks the Regex matches) but it takes a bit longer to fix and test.

**Comment by artem-sidorenko** [comment]
@crashbell @buunguyen great:) please let me know when I can destroy the test instance

**Comment by artem-sidorenko** [comment]
I destroyed the instance as it wasn't used and probably not needed anymore

**Comment by crashbell** [comment]
@artem-sidorenko Sorry about the delay. I have been busy, can't complete it now.

**Comment by ostrokach** [comment]
I ran into the same issue (only my GitLab installation is under `/git`, not `/gitlab`. Octotree does not work at all when I navigate to that site. It works great for github.com and gitlab.com.

**Comment by buunguyen** [comment]
Thanks for reporting this. As of v2.1.0, Octotree no longer supports GitLab. Please see more details here: https://github.com/buunguyen/octotree/blob/master/README.md#octotree.
