### ISSUE TITLE
Extension cause auto-reload on tab

### ISSUE THREAD

**Issue by khanhicetea** [buunguyen/octotree#296]
It causes auto-reload on tab if I try to make a Pull Request on Github or Merge Request on Gitlab.

I have to temporary disable extension to make a PR or MR.

**Comment by buunguyen** [comment]
Just made a PR in GitHub, don't see this problem.

**Comment by khanhicetea** [comment]
Sometimes I met this bug on Github, but it always happens on GitLab.

I recorded a video (30s) about this bug here : https://youtu.be/IvaknjDDVCA

**Comment by buunguyen** [comment]
@crashbell can you help with this on GitLab?

Note: I can't reproduce with GitHub at all, tried many times.

**Comment by buunguyen** [comment]
Thanks for reporting this. As of v2.1.0, Octotree no longer supports GitLab. Please see more details here: https://github.com/buunguyen/octotree/blob/master/README.md#octotree.
