### ISSUE TITLE
Submodule links in GitLab

### ISSUE THREAD

**Issue by kgram** [buunguyen/octotree#297]
Given a project `group/proj1` referencing another project `group/proj2` as a submodule, it seems Octotree links to `group/proj1/proj2` in the proj1-tree.

This was observed on an enterprise installation of GitLab.

**Comment by buunguyen** [comment]
Thanks for reporting this. As of v2.1.0, Octotree no longer supports GitLab. Please see more details here: https://github.com/buunguyen/octotree/blob/master/README.md#octotree.
