### ISSUE TITLE
Always show Invalid token

### ISSUE THREAD

**Issue by countcain** [buunguyen/octotree#298]
Hello,

First of all. This is an awesome repo/project! I installed the newest version on Chrome. No matter which github repo pages I open, the extension always require me input the token. After I re-generating the token and fill in the token, it keeps showing invalid token. I used the same token in this extension but in Safari, everything goes well.

Anyone come into this issue?

**Comment by buunguyen** [comment]
Strange. Just download latest version on Chrome and can browse fine without any access token.

Any specific repo that causes the problem? What does the console print?

**Comment by countcain** [comment]
Oh. I got the answer. I use ModHeader, a chrome extension to customize http request header. And I configured the http basic auth header.

If I turn on the http basic auth header for every request, the issues I mentioned above will occur. There are 401 Unauthoriztion error on the console.
If not, everything goes fine.

Here is the screenshots:

<img width="1660" alt="screen shot 2016-05-24 at 1 48 27 am" src="https://cloud.githubusercontent.com/assets/1751150/15493401/dd26ad6c-2151-11e6-8d78-12915b520630.png">
<img width="1660" alt="screen shot 2016-05-24 at 1 48 47 am" src="https://cloud.githubusercontent.com/assets/1751150/15493404/e1811794-2151-11e6-8290-83ebfc0ff8b0.png">

Take it for references. 

Thanks.

I will close the issue.

**Comment by robertohuertasm** [comment]
I'm getting the same issue in Firefox, only while browsing Github. Gitlab works perfectly. This screenshot was take while browsing your repo :wink: 

![capture](https://cloud.githubusercontent.com/assets/696981/17694914/703f3b00-63a6-11e6-8ba5-19535caa50fe.PNG)

**Comment by robertohuertasm** [comment]
Never mind, I reinstalled the extension, reintroduced the token and now it works. Thanks for this great extension! :+1:

**Comment by antronic** [comment]
@countcain I also using ModHeader and has a same issue. Lol

Thank for sharing

**Comment by kliyes** [comment]
@antronic So did I
