### ISSUE TITLE
Security issue - XSS through Octotree

### ISSUE THREAD

**Issue by brunocvcunha** [buunguyen/octotree#299]
Hi! 

There's a security flaw that compromises user data when using Octotree + GitHub.

The failure happens when you define a branch name that contains script - e.g. `<script>alert('xss')</script>`, define it as the default branch of the repo and navigate to an URL that doesn't contain the tree combobox (Issues, Pull Requests, Wiki, Stargazers, etc).

This repo has a harmless example: https://github.com/brunocvcunha/-script-alert-xaxa-script-/wiki
![image](https://cloud.githubusercontent.com/assets/3207647/16014192/90c6287e-3166-11e6-973f-d16f4d9f0d20.png)

Best Regards,
Bruno Candido Volpato da Cunha

**Comment by brunocvcunha** [comment]
@buunguyen

**Comment by buunguyen** [comment]
Which browser is this? I accessed the linked repo on Chrome, didn't see the popup.

**Comment by brunocvcunha** [comment]
Chrome 51.0.2704.84 (64-bit) on Mac OS X El Capitan.

![image](https://cloud.githubusercontent.com/assets/3207647/16025217/6facd7f6-319c-11e6-9093-911a99e517f9.png)

Maybe some XSS protection kicked in? If you look at the pasted printscreen with the DOM, the whole <script> tag is there.

**Comment by buunguyen** [comment]
Thanks, xss protection indeed. Already fixed and released, should be in stores soon.

**Comment by brunocvcunha** [comment]
Nice! Thank you!

**Comment by joedf** [comment]
Nice find :+1:
