### ISSUE TITLE
Error: Private repository

### ISSUE THREAD

**Issue by ajsb85** [buunguyen/octotree#300]
404 Link for the new token:
http://gitlab.xxxxx.infra/settings/tokens/new

I need fresh the site to see the button.

And appear an error.

![image](https://cloud.githubusercontent.com/assets/663460/16040357/529dc4c0-322f-11e6-86d9-1f1da37b0b36.png)

We are using: **GitLab Community Edition 8.8.4 `d4c3f17`**

**Comment by qsLI** [comment]
same issue

**Comment by ajsb85** [comment]
@qsLI I am using @FrankFan/gitlab-tree

**Comment by tillig** [comment]
Ran into this whilst browsing [files inside the Autofac.Mvc repo like this one](https://github.com/autofac/Autofac.Mvc/blob/develop/src/Autofac.Integration.Mvc/ModelBinderTypeAttribute.cs). At the [top level of the repo](https://github.com/autofac/Autofac.Mvc) the tree comes up just fine, but once you navigate into the code you get the private repo error.

Looking at the Chrome developer tools, I see that the repo URL to the file is `https://github.com/autofac/Autofac.Mvc/blob/develop/src/Autofac.Integration.Mvc/ModelBinderTypeAttribute.cs` but it's asking for `https://api.github.com/repos/src/Autofac.Integration.Mvc/git/trees/develop?recursive=1` which doesn't appear to be a valid query for the repo tree [based on the documentation](https://developer.github.com/v3/git/trees/).

**Comment by mattlorimor** [comment]
@tillig - I noticed this happening to me after the upgrade to 2.0.13. Downgrading to 2.0.12 seems to have fixed the problem for me.

**Comment by buunguyen** [comment]
@tillig @mattlorimor a bug in 2.0.13 indeed. I've reversed the change that causes this and published a new version. Should be available shortly. Thanks for reporting.

**Comment by appDork** [comment]
@buunguyen Updating to 2.0.14 seems to resolve the private repo error on my end. Thanks for the fix!

**Comment by imknown** [comment]
Empty branch 'gh-pages' will show this too.

**Comment by samnang** [comment]
@buunguyen Look like it happens again to me. I'm on `2.0.19`. It's just fine for master branch on private repo, but switching branches fails and shows invalid token.

**Comment by justin808** [comment]
I'm seeing this problem in 2.1.0.
