### ISSUE TITLE
Reserved User Names

### ISSUE THREAD

**Issue by Mottie** [buunguyen/octotree#304]
I'm not sure how important this is, but a few [`GH_RESERVED_USER_NAMES`](https://github.com/buunguyen/octotree/blob/master/src/adapters/github.js#L1-L10) are missing:

* https://github.com/business
* https://github.com/mirrors
* https://github.com/open-source
* https://github.com/personal
* https://github.com/pricing

```js
const GH_RESERVED_USER_NAMES = [
  'settings', 'orgs', 'organizations',
  'site', 'blog', 'about', 'explore',
  'styleguide', 'showcases', 'trending',
  'stars', 'dashboard', 'notifications',
  'search', 'developer', 'account',
  'pulls', 'issues', 'features', 'contact',
  'security', 'join', 'login', 'watching',
  'new', 'integrations', 'gist', 'business',
  'mirrors', 'open-source', 'personal',
  'pricing'
]
```

Also, I'm not really sure if the following are truly reserved

* https://github.com/gist
* https://github.com/orgs

**Comment by buunguyen** [comment]
Thanks for the new reserved names! I'll update the code. `gist` and `orgs` are indeed reserved, you can check by trying to sign up with those names.

**Comment by Mottie** [comment]
I found another one:  https://github.com/pages
