### ISSUE TITLE
mistakenly ask for private access token in files from organization/private repos

### ISSUE THREAD

**Issue by robturtle** [buunguyen/octotree#309]
Whenever I was reviewing a file from an organization/private repo, the plugin yield `Error: Private Repository` where I have a valid token already. This only happened when I'm into an end file and it works fine when I'm at some directory.

At organization repo:

![image](https://cloud.githubusercontent.com/assets/3524125/16932086/43e90432-4d12-11e6-8aca-9949f5b75c23.png)

![image](https://cloud.githubusercontent.com/assets/3524125/16932107/60a52baa-4d12-11e6-8731-a4857fb21a16.png)

At private repo:

![image](https://cloud.githubusercontent.com/assets/3524125/16932208/fc1078e2-4d12-11e6-8704-2d3f951be8a5.png)

![image](https://cloud.githubusercontent.com/assets/3524125/16932220/12704298-4d13-11e6-9871-001dac8a768c.png)

**Comment by buunguyen** [comment]
Thanks for reporting. I've just published an update that addresses the issue. Should be available shortly.

**Comment by robturtle** [comment]
It seems it's not related to the repo type. It only happened when accessing files where its name contains a dot char ('.')
