### ISSUE TITLE
Open randomly

### ISSUE THREAD

**Issue by Mte90** [buunguyen/octotree#311]
When i comment a ticket or pr if the sidebar is closed it is opened randomly also on the refresh of the page.
It is very annoying because with that there is the lost of the focus so i lost the text that i was writing....

**Comment by buunguyen** [comment]
What OS/browser? And GitHub or GitLab?

**Comment by Mte90** [comment]
With Firefox on github, it is happen right now opened and closed during the write of that ticket twice.
It is like that he don't rememeber the visibility, but to receive the event for open there is something strange

**Comment by buunguyen** [comment]
I don't see the problem with Firefox/OSX. Does it happen every time? Is there a particular repo that this happens?

**Comment by Mte90** [comment]
no happen with very repo and i cannot understand how to reproduce the error but is very annoying.
Happen everytime i try to write a comment in a ticket, maybe the workaround will be to not add the sidebar on that pages.

**Comment by buunguyen** [comment]
I know it's very annoying but unless I can reproduce, I can't do anything.

**Comment by Mte90** [comment]
I understand the problem but is possible to add an option to not add the sidebar in the issues/pr pages?

**Comment by Ephemera** [comment]
Use option **Show in non-code pages**

**Comment by Mte90** [comment]
I feel like a stupid for not saw that option before -.-'
