### ISSUE TITLE
Add option to autoexpand all trees, or a tiny button to make everything expand

### ISSUE THREAD

**Issue by yakrider** [buunguyen/octotree#318]
Often when browsing many small repos, it is painful to slowly dig through expanding all the buttons to get to the code you want. It would be great to have an option to auto-expand the tree, or trigger auto-expansion by clicking something.

If the worry is about very large trees, a sensible max can always be setup.. say max expansion to 100 or 1000 entries in total, and it stops expanding when it reaches that. Or maybe a limit to how deep it expands etc. Either way, for most normal use cases, we could set it to auto-expand while maintaining a max cap to avoid serious load. 

Seems like that could significantly improve the 90% use case!

**Comment by buunguyen** [comment]
There's an option to lazy load the tree. So it only loads the structure, then when you click on a directory, it will load the contents of that directory and no more.

**Comment by yakrider** [comment]
Right, but I dont just want the tree to be loaded, I want it to be loaded adn all the tree nodes expanded so I can scroll and see the files inside the folders rather than having to click 10 or 20 times to see what is inside each folder. 
I dont see anyway to set it to automatically expand the directories by default.. if there is soemthing we're missing do let us know!
