### ISSUE TITLE
TreeView branch not change after searching words in the 'This repository' on top.

### ISSUE THREAD

**Issue by imknown** [buunguyen/octotree#321]
I typed some words in the 'This repository' on top of one certain repository. 
Then I click the link of the repository name, the branch TreeView on the left does not change.

![issue](https://cloud.githubusercontent.com/assets/5681447/17991667/43fcbffc-6b73-11e6-93a3-d2353774dfef.png)

**Comment by buunguyen** [comment]
> Then I click the link of the repository nam

What link is this?

**Comment by imknown** [comment]
![animation](https://cloud.githubusercontent.com/assets/5681447/20006115/0c01ad98-a2d1-11e6-84ed-660c5aa59656.gif)

Hi, the above contains the operations~

**Comment by buunguyen** [comment]
Fixed with https://github.com/buunguyen/octotree/pull/359/files
