### ISSUE TITLE
Repo exclusion

### ISSUE THREAD

**Issue by galeksandrp** [buunguyen/octotree#323]
There are some repos that contains directories with >10000 files. Example https://github.com/EFForg/https-everywhere/tree/master/src/chrome/content/rules (30749). Therefore, if extension open when viewing folder or file in folder, it hang browser tab. Load entire tree at once have no effect because when viewing folder or file in folder extension should fetch & render all filenames in folder.

**Comment by buunguyen** [comment]
Go to Options, unselect "Load entire tree at once". Octotree will lazily populate the tree.
