### ISSUE TITLE
Octotree breaks hamburger menu overlay on GitLab

### ISSUE THREAD

**Issue by petetnt** [buunguyen/octotree#324]
Continuing from #319, now the button is correctly aligned but the overlay is broken on pages where there are multiple lines, for example Profile Settings or most repos:

With octotree:
![image](https://cloud.githubusercontent.com/assets/7641760/18491967/a8de7e2c-7a11-11e6-8c76-c4d6139518a3.png)

Without octotree: 
![image](https://cloud.githubusercontent.com/assets/7641760/18492015/dd082dd8-7a11-11e6-89b2-7272c9b310eb.png)

**Comment by Zhomart** [comment]
Most likely it's because of the update. Current version of Gitlab on gitlab.com is `8.12.0-rc2-ee` https://gitlab.com/help.

**Comment by buunguyen** [comment]
Fixed in 2.0.17
