### ISSUE TITLE
Feature request: allow clickthrough to directories, not just files

### ISSUE THREAD

**Issue by agreene5** [buunguyen/octotree#326]
The tree currently only allows you to jump to a file, but not to a directory. It would be a neat feature to be able to click through to a directory, so you can view the files in the traditional browser view.

**Comment by buunguyen** [comment]
Why is it better than the current behavior?

**Comment by agreene5** [comment]
One reason would be because you have a README.md in that directory, and would like to see the README.md in context with the files and their commit notes / change dates. Right now you could first click the README.md, then go to the file, but you would not see the whole picture at once.

If it's a good deal of effort to then I would say don't bother, but if not, I do think it has value. Maybe that's just me ;)

Unrelated: Thanks for the tool, it's really nice, though it took a little while for me to get it working on my internal GHE instance. There was some little quirk with configuring the token, even though I followed the instructions. I wish I could reproduce the issue to help improve the documentation. I repeated the same process maybe a dozen times, and then it just started working when I was about to give up
