### ISSUE TITLE
Octotree breaks dropdown menu on GitLab

### ISSUE THREAD

**Issue by Lacerda** [buunguyen/octotree#329]
In GitLab, the profile dropdown menu, in the issues page, is **pop-under** rather than **pop-over**.

This only happens with **octotree enabled.**

Check this issue for more information: https://gitlab.com/gitlab-org/gitlab-ce/issues/22606

**Comment by Ephemera** [comment]
Which version do you have?
I don't see that situation in 2.0.17

**Comment by buunguyen** [comment]
Can't reproduce either. Please specify version of Octotree & OS/browser.
