### ISSUE TITLE
[2.0.17] keeps asking for tokens on GitLab Enterprise Edition 8.11.4 

### ISSUE THREAD

**Issue by wizzard0** [buunguyen/octotree#330]
well, subj. also in general API paths are different (eg not /api/v3/repos but /api/v3/projects )

**Comment by minweidong** [comment]
-well

**Comment by minweidong** [comment]
- well

**Comment by simonedavico** [comment]
+1, I can't go past the token request view.

**Comment by webyneter** [comment]
+1, stuck with a token request view in Community Edition.

**Comment by buunguyen** [comment]
I don't have a GL deployment to test. Much appreciate a PR for this.

**Comment by brisssou** [comment]
I may try something, but I find it strange that the TOKEN is uniq for the whole context.

You could potentially have a token per GitHub enterprise/GitLAB URL, don't you think?

This would imply a few changes in the settings UI.

**Comment by lmj0011** [comment]
this error is still present in v2.0.21 

I believe the extension is still thinking it's on a github page

**Comment by brisssou** [comment]
OK, it does not make any sense, but it is now working, at least for me.
My company is using an inhouse hosted GitLab Community Edition 8.12.0.

In options, I don't have any GitHub Enterprise setup, I just have the `octotree.accessToken` valued OK.

I'm speechless, but it works.
If needed, I can of course dig deeper.

Feel free to ask for any question.

**Comment by lmj0011** [comment]
@brisssou 

Yea, still doesn't work for Gitlab Enterprise Edition because of https://github.com/buunguyen/octotree/issues/330#issue-179500015

**Comment by buunguyen** [comment]
Thanks for reporting this. As of v2.1.0, Octotree no longer supports GitLab. Please see more details here: https://github.com/buunguyen/octotree/blob/master/README.md#octotree.

**Comment by lmj0011** [comment]
Thanks for the closure
