### ISSUE TITLE
Manu-control the width of the tool

### ISSUE THREAD

**Issue by irmowan** [buunguyen/octotree#334]
Sometimes when the widget unfolds, it is too wide and has bad effect on viewing the original page. If one could change the width manually it will be better.

**Comment by buunguyen** [comment]
You can resize the sidebar.

**Comment by for-coursera** [comment]
But is it possible to somehow store the width? Some CSS hack, may be?

**Comment by buunguyen** [comment]
@for-coursera I don't understand your question. The sidebar width is currently persisted.

**Comment by for-coursera** [comment]
But if you narrow it (or -- probably -- widen), the setting won't be saved on a new launch of a browser (Firefox in my case).

**Comment by buunguyen** [comment]
Strange, it should save. Are you using in incognito or something? Check localStorage for the value.

**Comment by for-coursera** [comment]
No, no incognito or anything strange (third-party cookies are disabled, though).

Could you please guide on checking localStorage?

**Comment by unluisco** [comment]
@for-coursera in web console
`localStorage.setItem('octotree.sidebar_width', 250)`

**Comment by for-coursera** [comment]
Yeah, thanks, figured that already some time ago. After all, just formalized it as a "patch" for Greasemonkey :).
