### ISSUE TITLE
Token invalid even when all permissions are granted

### ISSUE THREAD

**Issue by apopiak** [buunguyen/octotree#336]
octotree complains about any token being invalid.
What could be the reason for that besides permissions? (as I already tried giving all possible permissions)

**Comment by crashbell** [comment]
You may need to see this: https://github.com/buunguyen/octotree#access-token

**Comment by apopiak** [comment]
I already consulted the readme and followed the instructions. Afterwards I
get the invalid token message. (Even with all permissions)

**Comment by buunguyen** [comment]
GitHub or GitLab, and did you create the token in the enterprise site or github.com/gitlab.com?

**Comment by apopiak** [comment]
GitHub and no enterprise.
I used the link in the error message to get a token. (Using the Firefox
add-on on GitHub)

**Comment by buunguyen** [comment]
Can you double-check the token? Make sure there's no leading or trailing space. I used to have a problem with copying/pasting where the token gets the leading space, causing the error.

**Comment by apopiak** [comment]
That fixed it. Can't believe I overlooked that space.
Sry to bother you :-)
Soooo how about adding a strip spaces call? ;-)
