### ISSUE TITLE
Extension won't install in Safari

### ISSUE THREAD

**Issue by TimSoethout** [buunguyen/octotree#338]
I downloaded the extension from the link in the readme.
Safari gives me a popup to trust octotree, which I accept. Then nothing happens and it does now show up in the extensions list.
I see these messages in the console:

```
20/10/16 11:48:30,253 Safari[31761]: Error: this application, or a library it uses, has passed an invalid numeric value (NaN, or not-a-number) to CoreGraphics API and this value is being ignored.Please fix this problem.
20/10/16 11:48:30,253 Safari[31761]: Error: this application, or a library it uses, has passed an invalid numeric value (NaN, or not-a-number) to CoreGraphics API and this value is being ignored.Please fix this problem.
20/10/16 11:48:30,253 Safari[31761]: Error: this application, or a library it uses, has passed an invalid numeric value (NaN, or not-a-number) to CoreGraphics API and this value is being ignored.Please fix this problem.
20/10/16 11:48:30,253 Safari[31761]: Error: this application, or a library it uses, has passed an invalid numeric value (NaN, or not-a-number) to CoreGraphics API and this value is being ignored.Please fix this problem.
20/10/16 11:48:30,253 Safari[31761]: Error: this application, or a library it uses, has passed an invalid numeric value (NaN, or not-a-number) to CoreGraphics API and this value is being ignored.Please fix this problem.
20/10/16 11:48:30,253 Safari[31761]: Error: this application, or a library it uses, has passed an invalid numeric value (NaN, or not-a-number) to CoreGraphics API and this value is being ignored.Please fix this problem.
```

I run Safari Version 9.1.3 (11601.7.8) on OSX 10.11.6 El Capitan.

**Comment by buunguyen** [comment]
I don't have Safari 9 to test, but the current file works fine with Safari 10 on El Capitan. Also another user had problem and restarting machine helped. Hope it helps.

**Comment by Cosaquee** [comment]
I have safari 10 and macOS Sierra and I have the same problem.

**Comment by buunguyen** [comment]
Please see this https://github.com/buunguyen/octotree/issues/341#issuecomment-258045181

**Comment by thomasglachant** [comment]
I have safari 10.0.1 and macOS Sierra. It doesn't work too. 
It ask me to trust the extension and then ... nothing !

**Comment by buunguyen** [comment]
Sorry to hear. I can't reproduce this on my machine and have no clue what the problem is. Any help/PR/idea is welcome.

BTW, thumb down a link about how another user solved the problem doesn't help. Better if you said what you tried.

**Comment by oderwat** [comment]
Same as @thomasglachant said. I can't find anything in the logs about it. Sierra was clean install. No big changes to the system so far.

**Comment by Ephemera** [comment]
I think it's OS issue (works fine to me. macOS 10.12/Safari 10.0)
See this [article](https://discussions.apple.com/thread/7254177)

**Comment by oderwat** [comment]
@Ephemera Not really. I can install other extensions and your article is from Oct 2015 and about missing links in Safari 9.

My guts say it may have to do with localisation. Because if it works on some systems and not on others, this is one of the things which are different, even if there are no other modifications to the system.
