### ISSUE TITLE
Add Issue template

### ISSUE THREAD

**Issue by karuppiah7890** [buunguyen/octotree#340]
@buunguyen It's a good practice to add Github Issue Templates, so that you can ask questions like

**Bug or feature request ?**

**For Bugs answer these questions**
**What did you do ?**
**What happened ?**
**What did you expect to happen ?**

**System Information**
**OS (including version) :**
**Browser (including version) :**

**Screenshots if any :**

Shall I add it ?

**Comment by buunguyen** [comment]
Thanks for the recommendation. I've added a simple issue & PR templates already.
