### ISSUE TITLE
Cannot installed on Safari Version 10.0.1 (12602.2.14.0.7)

### ISSUE THREAD

**Issue by ileodo** [buunguyen/octotree#341]
after clicking install, it didn't shown in the extension list.

**Comment by buunguyen** [comment]
I have exact version and it works. Maybe go to Preferences > Extensions to see if it's there.

**Comment by ileodo** [comment]
@buunguyen No, it's not there. It may happen when new installing?

**Comment by buunguyen** [comment]
I'm not sure. I uninstall the extension, then download from dist and double-click, it works. Maybe restart Safari/machine to see if any luck.

**Comment by ileodo** [comment]
solved after restart os

**Comment by buunguyen** [comment]
Great, thanks for the update.
