### ISSUE TITLE
[Enhancement] accessToken for different site urls

### ISSUE THREAD

**Issue by ileodo** [buunguyen/octotree#343]
Enhancement & Feature

How about allowing user to set accessToken for different site urls.

**Comment by buunguyen** [comment]
You mean different enterprise sites? Or different repos?

**Comment by ileodo** [comment]
For different sites, some people will work on both github.com and enterprise site at the same time.

**Comment by buunguyen** [comment]
That's already supported (Chrome & Opera only). Access token is unique per site and must be configured in the Octotree sidebar in that site.
