### ISSUE TITLE
It looks wired when octotree is open, the right side is empty.

### ISSUE THREAD

**Issue by prettyxw** [buunguyen/octotree#345]
### Description

Hi, it looks wired when octotree is open, the right side is empty. Is it possible to put the page content in the middle?

### Environment

* Octotree version: v2.0.17
* Browser & version: Safari v10.0.1
* OS & version: macOS Sierra v10.12.1

<img width="1567" alt="2016-11-09 10 25 11" src="https://cloud.githubusercontent.com/assets/8643953/20141462/69249a64-a6cb-11e6-998b-2013b7d4138e.png">

**Comment by buunguyen** [comment]
It's intended that way, so that when octotree shows/hide, it doesn't push/pull the layout too much, which causes flickering.
