### ISSUE TITLE
Error: API limit exceeded

### ISSUE THREAD

**Issue by jing2si** [buunguyen/octotree#350]
![sp161201_105419](https://cloud.githubusercontent.com/assets/2288824/20780272/c09db150-b7b4-11e6-999c-6b392ef40a51.png)

**Comment by HongJinBom** [comment]
The repo may be private repo. you should paste the your access token

**Comment by scilganon** [comment]
@jing2si answer, plz, next question:
- why don't you want to follow instruction? 
- what is the reason of creating issue? 
- what solution could you offer?

**Comment by jing2si** [comment]
@scilganon sorry, i don't follow instruction.Please close this issue.

**Comment by gluons** [comment]
@jing2si You can close your issue by yourself.

**Comment by scilganon** [comment]
@jing2si np, be attentively :) could you follow adive of @gluons and close task?
