### ISSUE TITLE
add search params setttings?

### ISSUE THREAD

**Issue by nuintun** [buunguyen/octotree#351]
I want to add a search params  ```ts=2``` to url, but there no way can setting.

>no ```ts=2```
https://github.com/rollup/rollup/blob/master/src/ExternalModule.js

>with ```ts=2```
https://github.com/rollup/rollup/blob/master/src/ExternalModule.js?ts=2

**Comment by buunguyen** [comment]
Check out https://chrome.google.com/webstore/detail/tab-size-on-github/ofjbgncegkdemndciafljngjbdpfmbkn
