### ISSUE TITLE
Project properties button is hidden on Gitlab

### ISSUE THREAD

**Issue by emerout** [buunguyen/octotree#354]
### Description
On Gitlab (public gitlab.com or Community Edition), when octotree is open, project properties button is hidden  (right align)

### Environment (if bug)

* Octotree version: 2.0.17
* Browser & version: Google Chrome Version 55.0.2883.75 m
* OS & version: Windows 7
* Screenshot

![capture1](https://cloud.githubusercontent.com/assets/4293490/21174031/23491ae4-c1db-11e6-94a4-7d9e86b11fbe.PNG)

![capture2](https://cloud.githubusercontent.com/assets/4293490/21173841/19c14da8-c1da-11e6-9558-32ba84262681.PNG)

**Comment by buunguyen** [comment]
Published fix to store. Should be available shortly. Thanks for reporting!
