### ISSUE TITLE
Disabled on my Chrome

### ISSUE THREAD

**Issue by tonghuashuo** [buunguyen/octotree#355]
I installed octotree 2.0.15 from Google Web Store yesterday. It worked then. but after I quit and relaunched Chrome. it became disable.

I'm using
- Chrome 57.0.2950.4 dev (64-bit)
- on my macOS 10.12.2
- octotree 2.0.15 

The chrome extension page says "This extension is not listed on Chrome Web Store. Might be installed without notice. (该扩展程序未列在 Chrome 网上应用店中，并可能是在您不知情的情况下添加的。"). I DID INSTALLED IT. now there's no option for my to enable it. (the enable button won't work)

![wx20161221-100731](https://cloud.githubusercontent.com/assets/6594276/21375330/c01957d0-c767-11e6-93da-adf14d1f7a3a.png)

Funny thing is. it works just fine on my QQBrowser 4.1.4132.400 (64-bit, based on Chromium 50.0.2661.75)

Octotree is very useful to me. Never felt github was lack of this feature until octotree showed up. And now it feels strange to use github without octotree. PLEASE help me get it back on Chrome.

**Comment by QinJiangbo** [comment]
I have met the same situation, and when I go to the chrome extension store, I can't install the extension online for "image resolving error"???

**Comment by taksakorn** [comment]
thank you

**Comment by buunguyen** [comment]
Hmm, this is strange. The latest version is 2.0.17, not 15. Also, I've published to all countries, but sounds like the China store has issue.

**Comment by tonghuashuo** [comment]
I upgraded to 2.0.17. So far it's been working well. hope this solves the problem.

I haven't tried developing an Chrome extension so I'm not sure whether this should happen. but 2.0.15 and 2.0.17 exists at the same time on my Chrome. just letting you know.
![octotree](https://cloud.githubusercontent.com/assets/6594276/21495628/b0018bce-cc53-11e6-9589-ea6316a945be.png)

**Comment by tonghuashuo** [comment]
I upgraded to 2.0.17. So far it's been working well. hope this solves the problem.

I haven't tried developing an Chrome extension so I'm not sure whether this should happen. but 2.0.15 and 2.0.17 exists at the same time on my Chrome. just letting you know.
![octotree](https://cloud.githubusercontent.com/assets/6594276/21495628/b0018bce-cc53-11e6-9589-ea6316a945be.png)

**Comment by buunguyen** [comment]
I don't know either. They shouldn't co-exist, certainly not in the US store AFAIK. 
I guess the solution to this is making sure you use the latest version, i.e. 2.0.17 as of now.
