### ISSUE TITLE
Not compatible with multiprocess

### ISSUE THREAD

**Issue by gluons** [buunguyen/octotree#356]
### Description
[Add-on Compatibility Reporter](https://addons.mozilla.org/en-US/firefox/addon/add-on-compatibility-reporter/) report that this addon is **not compatible with multiprocess**.

### Environment (if bug)

* **Octotree version:** 2.0.16
* **Browser & version:** Firefox Beta 51.0b10 (64-bit)
* **OS & version:** Windows 10 Pro (64bits)
* **Screenshot**, if any (drag an image here)
<img width="794" alt="d44ef1a6-c398-11e6-828e-acace7a685f4" src="https://cloud.githubusercontent.com/assets/4688092/21489168/f5866fb4-cc19-11e6-8247-460713a5193a.PNG">

**Comment by mikhoul** [comment]
https://addons.mozilla.org/en-US/firefox/compatibility/reporter/jid1-Om7eJGwA1U8Akg%40jetpack

**Comment by gluons** [comment]
Not hard. I've created PR to fix it. 🎉

**Comment by miltador** [comment]
+1 on this. Please merge #361 to make this awesome extension useful with Firefox and e10s

**Comment by gluons** [comment]
@buunguyen Currently, the version on AMO is 2.0.18. 🦊
Did Mozilla start reviewing your submission? 🤤

**Comment by buunguyen** [comment]
Yeah, it's under review. The queue seems very long this time (although even normally it's a long process with Mozilla), I guess many people are being affected by the recent changes.

**Comment by gluons** [comment]
OK. Thank you very much. 🙇

**Comment by buunguyen** [comment]
2.0.20 was just approved and available for download!

**Comment by gluons** [comment]
I got it. Thank you for informing me. 🎉 

<img width="721" alt="2" src="https://cloud.githubusercontent.com/assets/4688092/23148508/d4961b62-f818-11e6-973c-8e506983fa40.PNG">

<img width="724" alt="default" src="https://cloud.githubusercontent.com/assets/4688092/23148476/ae334490-f818-11e6-9e5d-48414a39895f.PNG">
