### ISSUE TITLE
Change branch in creating merge-request reloads page

### ISSUE THREAD

**Issue by stevengunneweg** [buunguyen/octotree#360]
When I create a new merge request and change either the source or destination branch the page reloads and my change in selection is reset. So with Octotree enabled I can't actually create a merge-request

* Octotree version:  2.0.18
* Browser & version: Chrome 55.0.2883.95 (64-bit)
* OS & version: OSX 10.11.6

**Comment by buunguyen** [comment]
I can't seem to reproduce. Still able to create merge request among different branches just fine. Any more info to help reproduce?

**Comment by stevengunneweg** [comment]
Hi @buunguyen , thanks for your reply.

Steps to reproduce:
- open gitlab with Octotree enabled
- create a new merge request
- change source or target branch

What happens:
The page reloads and the branch I just selected is no longer selected.

What is expected:
The page does not reload and acts as if Octotree wasn't there.

These are the requests that are being fired when I select a different branch
<img width="808" alt="screen shot 2017-01-25 at 4 55 07 pm" src="https://cloud.githubusercontent.com/assets/3081489/22298035/62db5572-e31f-11e6-9781-a24e860f7396.png">

I'm not quite sure what more information I could give you to help reproduce the issue.

**Comment by buunguyen** [comment]
Thanks for reporting this. As of v2.1.0, Octotree no longer supports GitLab. Please see more details here: https://github.com/buunguyen/octotree/blob/master/README.md#octotree.
