### ISSUE TITLE
Cannot connect to website through an HTTP proxy: Error: Connection error

### ISSUE THREAD

**Issue by nonoroazoro** [buunguyen/octotree#362]
### Description

I can access GitHub through **AutoProxy (an extension of Firefox)**, but It seems that Octotree doesn't connect to Internet through the proxy even if I set to **Global Proxy Mode**.

```
Error: Connection error
Cannot connect to website. If your network connection to this website is fine, maybe there is an outage of the API. Please try again later.
```

1. Firefiox, using **AutoProxy in Global Proxy Mode**.
1. Open Octotree's sidebar.

### Environment

* Octotree version: **2.0.18**
* Browser & version: **Firefox 51.0.1 x64 with AutoProxy**
* OS & version: **OSX 10.11.6**

**Comment by buunguyen** [comment]
I'm closing this now. If this still happens with the latest version of Firefox and Octotree, please resubmit. However, I'm not sure if it has anything to do with Octotree, which just uses jQuery to make Ajax calls.
