### ISSUE TITLE
GitLab: menu indented without button

### ISSUE THREAD

**Issue by morkro** [buunguyen/octotree#364]
### Description
When browsing GitLab with OctoTree the upper left menu item is always indented although there is no OctoTree button. On repositories the button is there and everything looks fine again.
I've included a screenshot below.

### Environment (if bug)

* Octotree version: `2.0.19`
* Browser & version: Chrome 56
* OS & version: OS X El Capitan 10.11.6
* Screenshot:

<img width="854" alt="screen shot 2017-02-06 at 16 18 34" src="https://cloud.githubusercontent.com/assets/2461956/22652767/fe471264-ec87-11e6-915e-81ad83465fcf.png">

**Comment by g3d** [comment]
:+1: same issue

**Comment by buunguyen** [comment]
Thanks for reporting this. As of v2.1.0, Octotree no longer supports GitLab. Please see more details here: https://github.com/buunguyen/octotree/blob/master/README.md#octotree.

**Comment by morkro** [comment]
Thanks for keeping us updated on this 🎉
