### ISSUE TITLE
Adding a personal access token no longer grants access to private repo

### ISSUE THREAD

**Issue by walkermalling** [buunguyen/octotree#365]
### Description

Adding a personal access token to access a private repository no longer grants access.  Clicking 'save' returns the same error state "Error: Private repository" for the sidebar.  Generating a new token does not change this behavior.

Additional Notes: 

When this started happening a few days ago, I only got an error when looking at non-master branches on the repo; when looking at master branch, octotree was able to display the file tree of the private repo.

Now it is true for any private repo + branch

### Environment (if bug)

* Octotree version: 2.0.19
* Browser & version:  Chrome 56.0.2924.87 (64-bit)
* OS & version: OSX Yosemite 10.10.5 (14F2109)

**Comment by buunguyen** [comment]
Thanks for reporting. I've just uploaded a new version (2.0.20) that fixes this issue. It should be available in Chrome store shortly.

**Comment by walkermalling** [comment]
I'm still having this issue with Octotree 2.0.20

**Comment by buunguyen** [comment]
If you can reproduce with a public repo, please send me link to that repo.

**Comment by buunguyen** [comment]
I can't reproduce. All private repos work fine. If you have more info to help reproduce, let me know. Also please capture the error in console, there's should be an XHR request failure.

**Comment by walkermalling** [comment]
![screen shot 2017-02-13 at 9 43 57 am 2](https://cloud.githubusercontent.com/assets/8099432/22895704/51d49ede-f1d2-11e6-839c-562e0a2325c4.png)

@buunguyen

**Comment by buunguyen** [comment]
That's the master branch? What's the error?

**Comment by walkermalling** [comment]
Yes, this is master branch.

The `404` response body is simply:
```
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}
```

Network tab has 2 entries, one shows `204` (no content) and the other a `404` response.

Request url is `https://api.github.com/repos/<my repo>/git/trees/master?recursive=1&_=1487011401797`

**Comment by DzmitryShylovich** [comment]
I have the same issue only on `Pull requests` page

**Comment by DzmitryShylovich** [comment]
@buunguyen I have the same issue only on `Pull requests` page http://prntscr.com/ebgfzu

**Comment by AntSworD** [comment]
I have the same issue, some time for a private project, sometime for a public project. Most of time was fine!

**Comment by buunguyen** [comment]
@DzmitryShylovich there's indeed a problem in PR page, reported separate here https://github.com/buunguyen/octotree/issues/377

**Comment by nickforddesign** [comment]
I'm having this problem suddenly as well

**Comment by SirPhemmiey** [comment]
Any fix for this problem?
