### ISSUE TITLE
How to use within the intranet (like: http://gitlab.intranet)

### ISSUE THREAD

**Issue by candido1212** [buunguyen/octotree#366]
### Description
How enable this, into a gitlab within my intranet (http://gitlab.intranet)

**Comment by buunguyen** [comment]
Have you tried https://github.com/buunguyen/octotree#enterprise-urls?

**Comment by piRGoif** [comment]
Hi, I'm facing exactly the same problem...

When connected to our Gitlab (hosted in our company in our intranet), no Octotree icon appears at all... So I cannot access the settings of the app...

When connected to any Gitlab.com repo (like the one you propose to use, https://gitlab.com/gitlab-org/gitlab-ce) the settings pane contains two fields : "Site access token" and "Hotkeys". No fields for a site URL...

When pressing the hotkey the dev tools appear... I tried adding another hotkey but same result...

**Comment by 0x62ash** [comment]
I've tried to generate personal access token (https://gitlab.local/profile/personal_access_tokens) but without success :(

**Comment by buunguyen** [comment]
Thanks for reporting this. As of v2.1.0, Octotree no longer supports GitLab. Please see more details here: https://github.com/buunguyen/octotree/blob/master/README.md#octotree.
