### ISSUE TITLE
crash on the latest version of Chrome

### ISSUE THREAD

**Issue by misakuo** [buunguyen/octotree#369]
Very frequent crashes.

* Octotree version: 2.0.20
* Browser & version: 56.0.2924.87 (64-bit)
* OS & version: OS X EI Capitan 10.11.6

**Comment by buunguyen** [comment]
Does it happen in incognito with only Octotree running? I wonder if there's another extension causing some sort of conflict.

**Comment by misakuo** [comment]
Looks like the `vysor` plugin caused the problem, I'll close this issue.
