### ISSUE TITLE
Extension doesn't work with new Github UI

### ISSUE THREAD

**Issue by dinhtungdu** [buunguyen/octotree#370]
### Description
As title says.

### Environment (if bug)

* Octotree version: 2.0.20
* Browser & version: Chrome 56.0.2924.87 (64-bit)
* OS & version: OSX 10.11.6
* Screenshot, if any (drag an image here): http://prntscr.com/e8w906

**Comment by buunguyen** [comment]
Weird, works fine here. Any error in console? Does it show on other pages?

**Comment by Saketme** [comment]
Same here. It worked fine for a few days when the new Github UI rolled out, but I can no longer see it. @buunguyen I don't see anything in the console:

<img width="615" alt="screen shot 2017-02-15 at 12 41 06 pm" src="https://cloud.githubusercontent.com/assets/2387680/22963971/22aa5a12-f37c-11e6-84aa-e4f38fff7e49.png">

**Comment by buunguyen** [comment]
I have no problem. Would need more info.

**Comment by dinhtungdu** [comment]
I'm tested on Private browsing without other extensions, it's worked.
This problem caused by other extension. I'll close it now.

**Comment by Saketme** [comment]
Update: I had to re-enable the plugin to make it work.
