### ISSUE TITLE
Support Gogs

### ISSUE THREAD

**Issue by wind0ws** [buunguyen/octotree#371]
Love the awesome extension so much!

Maybe it would be great if it also displayed a tree for Gogs repos. 👍 
 
Thanks for your effort!

**Comment by lenormf** [comment]
I don't know if the code implementing `gogs` support would be cross compatible, but I would like `gitea` support as well if possible!

**Comment by buunguyen** [comment]
This is not in my plan at the moment. I'll gladly accept PR though.
