### ISSUE TITLE
Gitlab: Merge request change tab

### ISSUE THREAD

**Issue by theanht1** [buunguyen/octotree#372]
### Description
When access Gitlab merge request change tab with OctoTree, the menu is collapsed but the bar below is not.

### Environment (if bug)

* Octotree version:  `2.0.20`
* Browser & version: Chrome `56.0.2924.87`
* OS & version: Arch Linux 
* Screenshot
![gitlab-merge-request-diff-issue](https://cloud.githubusercontent.com/assets/11568632/23008088/cd2dc654-f43f-11e6-83ac-e3d1030379e3.png)

**Comment by buunguyen** [comment]
Thanks for reporting this. As of v2.1.0, Octotree no longer supports GitLab. Please see more details here: https://github.com/buunguyen/octotree/blob/master/README.md#octotree.
