### ISSUE TITLE
GitLab removed turbolinks

### ISSUE THREAD

**Issue by psimyn** [buunguyen/octotree#373]
### Description

GitLab recently removed turbolinks, now navigating between pages causes a bunch of stuff to not load. 

[GitLab CE issue](https://gitlab.com/gitlab-org/gitlab-ce/issues/28161)

### Environment (if bug)

* Octotree version: 2.0.20
* Browser & version: Chrome 56
* OS & version: All

**Comment by rolling-space** [comment]
+1(0000) for this. It renders `octotree` effectively non-functional for `gitlab` projects. :(

Is there maybe any hack in place -- like excluding a specific URL -- as for `octotree` to not inject itself on certain pages? I suspect that `gitlab` users will disable the extension until this is fixed.

**Comment by crashbell** [comment]
I don't meet any issue. Can someone please give me some clear steps? Tried to navigate some repos and do stuff but got nothing as an issue.

**Comment by buunguyen** [comment]
@crashbell have you checked this out? https://gitlab.com/gitlab-org/gitlab-ce/issues/28161

**Comment by crashbell** [comment]
@buunguyen I missed this 😞

**Comment by rolling-space** [comment]
@buunguyen @crashbell Guys, is this going to be given some priority?

**Comment by crashbell** [comment]
@rolling-space I'm working on that, @psimyn already made a PR but I think we need some improvement and backward compatible with GitLab enterprise versions.

**Comment by buunguyen** [comment]
Anyone knows what's the replacement for Turbolinks in GitLab? 

We need to still keep Ajax loading somehow.  If removing Turbolinks from Octotree, there must be an alternative to ajax-load the file, ideally piggy back on whatever mechanism GitLab uses to avoid work & possible conflicts.

**Comment by psimyn** [comment]
There isn't a full replacement for it. Ajax pages are still used in some places (e.g. Tabs on Merge Request page, and infinite scroll on Commits view). But most views now are full page loads again.

I assume you'd want extension to match that behaviour, so fix for the ajax views is still needed

**Comment by buunguyen** [comment]
Thanks for reporting this. As of v2.1.0, Octotree no longer supports GitLab. Please see more details here: https://github.com/buunguyen/octotree/blob/master/README.md#octotree.
