### ISSUE TITLE
Fuzzy finder like CtrlP

### ISSUE THREAD

**Issue by sw-double** [buunguyen/octotree#375]
Hello, there, great extension!
I thought it would be very cool to be able to go to file with fuzzy finder.
Although we must probably have entire tree loaded for this to work.
Do you think it is possible to implement?

**Comment by buunguyen** [comment]
Fuzzy finder as in the `t` shortcut already built-in to GitHub?

**Comment by sw-double** [comment]
Oh, thanks for the eye-opener
