### ISSUE TITLE
Pull request pages treated as private repositories

### ISSUE THREAD

**Issue by mgol** [buunguyen/octotree#377]
### Description
1. Go to https://github.com/jquery/api.jquery.com/pull/1025
2. Open the OctoTree sidebar

### Environment (if bug)

* Octotree version: 2.0.20
* Browser & version: Chrome  56.0.2924.87
* OS & version: macOS 10.12.3 (16D32)
* Screenshot, if any (drag an image here)
<img width="826" alt="screen shot 2017-02-23 at 16 58 52" src="https://cloud.githubusercontent.com/assets/1758366/23266895/679b5d92-f9e9-11e6-9d0a-a24bb813d952.png">

**Comment by buunguyen** [comment]
Fix in 2.0.21. Should be available in store soon.

**Comment by mgol** [comment]
Thanks! I confirm it works now.
