### ISSUE TITLE
[GitLab] Cannot reorder issues inside milestone view

### ISSUE THREAD

**Issue by carbolymer** [buunguyen/octotree#378]
When I'm trying to drag and drop issues in the same (or different) columns inside a milestone view nothing happens. 

## Steps to reproduce
1. Open milestones view for your project (relative path: `/milestones`)
1. Click on the first milestone
1. When hovering mouse over the issue, mouse is visible as pointer. Trying to drag has no effect. `<ul>` with the list does not have class `ui-sortable`. Console has HTTP GET request error, which contains `repositorynull` - probably erroneus string concatenation. More details on the attached screen.
    * User can refresh the page with the milestone view (relative path for example `/milestones/1`) and the issues are now draggable.
    * User can disable Octotree, and issues list is draggable.

Browser info:
```
Chromium	56.0.2924.87 (Developer Build) (64-bit)
Revision	b169b9a1cc402573843e8c952af14c4e43487e91
OS	        Linux 
JavaScript	V8 5.6.326.50
```

![stacktrace](https://cloud.githubusercontent.com/assets/228866/23368656/d556071a-fd0e-11e6-94b7-c0252d5e60a7.png)

**Comment by buunguyen** [comment]
Thanks for reporting this. As of v2.1.0, Octotree no longer supports GitLab. Please see more details here: https://github.com/buunguyen/octotree/blob/master/README.md#octotree.
