### ISSUE TITLE
"attach file" button in GitLab issues does not work while Octotree is enabled

### ISSUE THREAD

**Issue by MatD-IMG** [buunguyen/octotree#379]
### Description
While extension is active the "attach file" button in GitLab issues does not work and I also cannot pasted images straight into the GitLab Issues Description edit box. Removing the Octotree extension fixes the problem.

### Environment (if bug)

* Octotree version: 2.0.21
* Browser & version: Google Chrome 56.0.2924.87 (64-bit)
* OS & version: Windows 10 version (1607 build 14393.0)
* Screenshot, if any (drag an image here)

**Comment by buunguyen** [comment]
Thanks for reporting this. As of v2.1.0, Octotree no longer supports GitLab. Please see more details here: https://github.com/buunguyen/octotree/blob/master/README.md#octotree.
