### ISSUE TITLE
GitLab Issues > Boards doesn't work with Octotree enabled

### ISSUE THREAD

**Issue by ikromin** [buunguyen/octotree#381]
### Description
In GitLab: When navigating to Boards from the Issues URL, the board content is not loaded.

Steps to reproduce:
 1. Navigate to https://gitlab.com/gitlab-org/gitlab-ce/issues
 2. Click on Boards

OS: macOS Sierra 10.12.3
Browser: Safari 10.0.3

![screen shot 2017-03-02 at 09 34 06](https://cloud.githubusercontent.com/assets/14049131/23484804/a1faa43c-ff2c-11e6-9333-d6b7c161a328.png)

See original issue over at GitLab: https://gitlab.com/gitlab-org/gitlab-ce/issues/28730

If Octotree is disabled, this issue does goes away.

**Comment by adamgoose** [comment]
I'm experiencing something similar since GitLab 8.17.0 was released. Now running 8.17.2 and still having the same issue.

I happen to know that [GitLab has been slowly re-writing their front-end](https://about.gitlab.com/2016/10/20/why-we-chose-vue/) in [vue](http://vuejs.org/). Might this have something to do with it?

**Comment by buunguyen** [comment]
Yeah, GitLab is changing too much and I can't keep up. I'm not motivated to catch up given GitLab already said they'll build a similar feature https://github.com/buunguyen/octotree/issues/265.

**Comment by adamgoose** [comment]
Oh, that makes loads of sense! I absolutely love Octotree and am incredibly grateful for an excellent extension.

**Comment by ikromin** [comment]
Possible to add an option in OctoTree so that it is disabled on a GitLab site?

**Comment by buunguyen** [comment]
I think I would just remove GitLab support completely if it has become annoying for people on GitLab. Let me know any objection.

**Comment by ikromin** [comment]
I wouldn't go that far as it only affects a part of the GitLab interface, maybe a known issue note is all that's needed.

**Comment by buunguyen** [comment]
Thanks for reporting this. As of v2.1.0, Octotree no longer supports GitLab. Please see more details here: https://github.com/buunguyen/octotree/blob/master/README.md#octotree.

**Comment by zrvil43000** [comment]
แก้ไขสิ่งที่ผิดปรกติ
