### ISSUE TITLE
Feature Request: File tree for Pull Requests

### ISSUE THREAD

**Issue by stavfx** [buunguyen/octotree#382]
When looking at a pull request, I would like the file tree to only reflect files relevant to this request.
In a similar fashion to how Bitbucket / Fisheye does Pull Requests.
More enhancements might include:
* Clicking the file will jump to the diff of the pull request, rather than the full file source.
* Color file names according to add/delete/edit state.

Any degree of implementation of this feature would be highly appreciated! :)
Thanks!

**Comment by buunguyen** [comment]
Thanks for reporting this. As of v2.1.0, Octotree no longer supports GitLab. Please see more details here: https://github.com/buunguyen/octotree/blob/master/README.md#octotree.

**Comment by stavfx** [comment]
I was talking about GitHub
