### ISSUE TITLE
Private gitlab installation support?

### ISSUE THREAD

**Issue by aram535** [buunguyen/octotree#385]
Does Octotree support a private Gitlab CE install?

### Environment (if bug)

* Octotree version:  2.0.21
* Browser & version: Chrome 57.0.2987.88
* OS & version: Windows 10, 64

Tokens created by the user are not accepted.  I did change the URL to our HTTPS link.

**Comment by buunguyen** [comment]
Thanks for reporting this. As of v2.1.0, Octotree no longer supports GitLab. Please see more details here: https://github.com/buunguyen/octotree/blob/master/README.md#octotree.
