### ISSUE TITLE
Some contents float after extending octotree sidebar

### ISSUE THREAD

**Issue by sanjeevkpandit** [buunguyen/octotree#386]
### Description
I found out that some contents overlap after extending the sidebar of octotree. 

### Environment
* Octotree version:  2.0.21
* Browser & version: Google Chrome 56.0.2924.87 (64-bit)
* OS & version: Arch Linux 4.9.11-1-ARCH x86_64
* Screenshots
![using octotree extension](https://cloud.githubusercontent.com/assets/13619272/23738241/db76806c-04bf-11e7-9e90-a88ba6710d4c.png)
![without octotree extension](https://cloud.githubusercontent.com/assets/13619272/23738243/db7dfd38-04bf-11e7-98b7-3db5cadd6aea.png)

**Comment by buunguyen** [comment]
Thanks for reporting this. As of v2.1.0, Octotree no longer supports GitLab. Please see more details here: https://github.com/buunguyen/octotree/blob/master/README.md#octotree.
