### ISSUE TITLE
Generate access token link in GitLab returns 404

### ISSUE THREAD

**Issue by JRodDynamite** [buunguyen/octotree#387]
### Description
On a public repository in GitLab, I get an error.

> Accessing private repositories requires a access token. 
    Follow this link to create one and paste it below.

Issue is that when I click on the link, it redirects to https://gitlab.com/settings/tokens/new but it returns a 404 page. I believe the correct link to it is https://gitlab.com/profile/personal_access_tokens.

I think that changes would be required in `adapter/github.js` in the `getCreateTokenUrl()` method. Let me know if I'm right, I can help in submitting a PR. :smiley: 

### Environment (if bug)

* Octotree version: 2.1.0
* Browser & version: Chrome Version 54.0.2840.100 (64-bit)
* OS & version: Ubuntu 14.04

**Comment by nhajiyani** [comment]
Facing the same issue on Windows

**Comment by buunguyen** [comment]
Hi, do you still see Octotree in GitLab? It should not have been there since version 2.1.0.

**Comment by nhajiyani** [comment]
It kind of comes and goes, shows up on browser refresh.

**Comment by ankurk91** [comment]
@buunguyen 
I can confirm this issue.
I am using chrome 56, Ubuntu 16.04 x64, octotree 2.1.0.
See screenshot taken from a private repo on gitlab.
![screenshot from 2017-03-16 12-10-33](https://cloud.githubusercontent.com/assets/6111524/23984832/a2f7ea0a-0a41-11e7-9f85-58bcc5f84353.png)

**Comment by buunguyen** [comment]
Hmm, that's weird. Maybe Chrome cache the domains it injects the script. Please uninstall and add Octotree again. Please note Octotree no longer supports GitLab, from the README:

> GitLab is no longer supported: As of version 2.1.0, Octotree no longer supports GitLab. There are 2 reasons for this. First, GitLab has changed so much recently that it would take a lot of effort to keep Octotree up to date. Second, the GitLab team has told me they would build a tree feature in GitLab itself. I can't afford working on something knowing my effort will be irrelevant any time soon. That being said, if anyone wants to work on supporting the new GitLab, I'll gladly accept contributions to add back GitLab support.
