### ISSUE TITLE
Octotree stopped working on Gitlab

### ISSUE THREAD

**Issue by nhajiyani** [buunguyen/octotree#388]
### Description
Octotree just stopped working yesterday morning on Gitlab
I also tried adding in a new access token but still does not work.

* Octotree version:2.1.0
* Browser & version: Chrome Version 57.0.2987.98
* OS & version:Windows 7 Enterprise
* Screenshot, if any (drag an image here)
![octrotree-stoppedworking](https://cloud.githubusercontent.com/assets/835204/23929350/6d8a3e6c-08f3-11e7-84d3-b8182124ca7e.PNG)
 P.S. - I did change my access token from the one showing up in the image

**Comment by nhajiyani** [comment]
Ohh, sad to hear. Incase want to share why that changed - and if there is a way to change that in the future ?

Thanks

**Comment by buunguyen** [comment]
From the README:

GitLab is no longer supported: As of version 2.1.0, Octotree no longer supports GitLab. There are 2 reasons for this. First, GitLab has changed so much recently that it would take a lot of effort to keep Octotree up to date. Second, the GitLab team has told me they would build a tree feature in GitLab itself. I can't afford working on something knowing my effort will be irrelevant any time soon. That being said, if anyone wants to work on supporting the new GitLab, I'll gladly accept contributions to add back GitLab support.

**Comment by hanzichi** [comment]
but has not seen the  tree feature in GitLab yet

**Comment by bryce-ma** [comment]
> but has not seen the tree feature in GitLab yet

The GitLab IDE just do the tree feature I think.

**Comment by albacoretuna** [comment]
This is a new extension specifically for Gitlab if you came here by searching: 
https://github.com/tavyandy97/span-tree
