### ISSUE TITLE
Provide a WebExtension version for Firefox

### ISSUE THREAD

**Issue by Timvde** [buunguyen/octotree#392]
Mozilla will soon (Fx 57) deprecate the traditional, XUL-based add-on system. It will be replaced by WebExtensions, which are based on the Chrome APIs. Porting the add-on from Chrome should be very simple, as explained by [Mozilla's documentation](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension).

**Comment by buunguyen** [comment]
Great. There's hope for this issue https://github.com/buunguyen/octotree/issues/275.

Would be great if someone goes ahead making a PR.

**Comment by alex** [comment]
Octotree is one of my favorite extensions, thanks for your work on it!

Since legacy extensions were disabled on nightly last night, I'm without Octotree :-( Do you have any sense of when the latest version will be uploaded to addons.mozilla.org?

**Comment by buunguyen** [comment]
@alex can you try the adhoc build from dist/firefox.zip and see if it works?

**Comment by buunguyen** [comment]
I've just submitted 2.2.0 that supports WebExtensions to Mozilla Store. So hang tight while it's being reviewed.
