### ISSUE TITLE
Support Gitlab

### ISSUE THREAD

**Issue by mkeedlinger** [buunguyen/octotree#401]
Would love to see this there :smile:

Thanks for the great work!

(similar to #22)

**Comment by Ephemera** [comment]
Please read the [README](https://github.com/buunguyen/octotree/blob/master/README.md)

**Comment by mkeedlinger** [comment]
Ah. Totally get it.
Thanks!

**Comment by itsnotvalid** [comment]
Does reinstalling it remove the icon when visiting gitlab? thanks.

**Comment by mkeedlinger** [comment]
@itsnotvalid not sure what you mean.
