### ISSUE TITLE
Allow to navigate when click on class name?

### ISSUE THREAD

**Issue by anticafe** [buunguyen/octotree#404]
### Description
I see this article (https://medium.com/@droidchef/how-to-navigate-through-your-java-projects-on-github-like-a-boss-488a37e16310) looks interesting. He writes an extension which allows user clicks on class name, then jump to that file.
Can we integrate such feature into Octotree?

### Environment (if bug)

* Octotree version:
* Browser & version:
* OS & version:
* Screenshot, if any (drag an image here)

**Comment by buunguyen** [comment]
That's certainly a neat feature but I think it's out of the scope for Octotree. I'd rather other extensions do it and do it well.
