### ISSUE TITLE
github enterprise 2.9 use it

### ISSUE THREAD

**Issue by phpstudyOne** [buunguyen/octotree#408]
### Description

This plugin can only be used in making the website, how to use in making enterprise version?
### Environment (if bug)
github version :  enterprise 2.9

**Comment by xakraz** [comment]
+1 for GitHub Enterprise support !

**Comment by buunguyen** [comment]
Have you tried this https://github.com/buunguyen/octotree#enterprise-urls

**Comment by phpstudyOne** [comment]
@buunguyen  thanks a lot.
