### ISSUE TITLE
Support tag browsing

### ISSUE THREAD

**Issue by superslowloris** [buunguyen/octotree#409]
### Description
The current version of Octotree does not work when browsing tag. 
As an example, the tree for the following url: https://github.com/spetz/Depot/tree/1 does not load. But the extension works fine on master: https://github.com/spetz/Depot/tree/master

### Environment 
* Octotree version: 2.1.0
* Browser & version: 58.0.3029.110 (64-bit)
* OS & version: Windows 10 (1703)

**Comment by HongxuChen** [comment]
Actually I think Octotree only supports *master* branch for the time being. I quite often got confused when reviewing code on other branches 😭

**Comment by buunguyen** [comment]
Should have been fixed in 2.2.0, will release shortly.
