### ISSUE TITLE
Tree representation of Git history

### ISSUE THREAD

**Issue by kbariotis** [buunguyen/octotree#418]
Would it be possible to have a tree representation of the repository's Git history? Much like Sourcetree?

**Comment by crashbell** [comment]
Regarding the description of Octotree: 

> Browser extension (Chrome, Firefox, Opera and Safari) to show a code tree on GitHub. Awesome for exploring project source without having to pull every single repository to your machine.

A git history tree looks out of scope since Octotree was designed to help us view project structure quickly.

**Comment by kbariotis** [comment]
I see @crashbell! Indeed, I just thought I would be a good feature alongside the project structure.
