### ISSUE TITLE
[Firefox] Unable to hide tree.

### ISSUE THREAD

**Issue by gluons** [buunguyen/octotree#419]
### Description
Unable to hide tree after open. Tree appears full width. I can't do anything to reach the hide button.

### Environment (if bug)

* Octotree version: 2.1.0
* Browser & version: Firefox Developer Edition 55.0b10 (64 bits)
* OS & version: Windows 10 version 1703
* Screenshot, if any (drag an image here)
  ![2017-07-19_09-36-07](https://user-images.githubusercontent.com/4688092/28348309-8c1ae788-6c66-11e7-95a9-8d21d23d7424.gif)

**Comment by buunguyen** [comment]
Weird, not sure what caused it. You can temporarily fix by setting octotree.sidebar_width in local storage to something like 220.
