### ISSUE TITLE
Do not load extention on GitLab

### ISSUE THREAD

**Issue by kfreiman** [buunguyen/octotree#420]
### Description
Since GitLab is no longer supported, this extention should not be loaded on GitLab

### Environment (if bug)

* Octotree version: 2.1.0
* Browser & version: Chrome  58.0.3029.96 (64-bit)
* OS & version: Ubuntu 16.04
* Screenshot, if any (drag an image here) 
![84c9f3ceeb](https://user-images.githubusercontent.com/2056294/28614274-e0e97986-71fd-11e7-817d-a754a35682de.png)

**Comment by marsjaninzmarsa** [comment]
Weird, it should have been completely removed in 0aa79cd472182e34f648b8e6b99cd31a3f24c092 which is tagged `v2.1.0`, releases in `/src` also looks ok...

**Comment by buunguyen** [comment]
What @marsjaninzmarsa says :).

Does it still happen? Maybe trying uninstalling and installing it again?

**Comment by buunguyen** [comment]
Please try 2.2.0, if issue persists, please reopen.
