### ISSUE TITLE
Autohide on non-code pages

### ISSUE THREAD

**Issue by laughedelic** [buunguyen/octotree#421]
### Current behavior

There is a setting "Show on non-code pages", but if I turn it off the extension just doesn't load on those pages (or is completely hidden). 

### Feature request

I would like it to work (or to have another setting) so that the tree collapses on the non-code pages, but I can still open it (via the button or hotkey). 

### Motivation

While I'm browsing the code I'm using the tree all the time to jump between files, but when I go to the issues, the tree is not very useful and should collapse. Yet if I want to go back to browse the code, the tree should be accessible to jump to a certain file.

**Comment by buunguyen** [comment]
I see your point. But I don't like to have too many options and the browsing habit depends on people, specific repos and their needs at the time. I think the toggle short key is probably good enough :).
