### ISSUE TITLE
Octotree stopped working in Firefox Nightly

### ISSUE THREAD

**Issue by cmoud94** [buunguyen/octotree#422]
### Description
Perhaps there was something changed in Nightly because Octotree worked few days ago but now it doesn't work. Add-on itself is enabled and Firefox doesn't report any problems with addons, I've also tried looking inside developer tools but there was nothing as well. 

### Environment (if bug)

* Octotree version: 2.1.0
* Browser & version: Firefox Nightly (56.0a1)
* OS & version: Debian (testing/buster)

**Comment by buunguyen** [comment]
Can you try installing ad-hoc from /dist/firefox.zip and let me know if it works?

**Comment by cmoud94** [comment]
I'm unable to install it ad-hoc, also the AMO version is no longer supported in Nightly 57.0a1.

**Comment by gluons** [comment]
Same here. Just move to Nightly (FF 57) and can't install from AMO. I'm waiting for Firefox 57 compat version. 😅

**Comment by buunguyen** [comment]
I've just submitted 2.2.0 that supports WebExtensions to Mozilla Store. So hang tight while it's being reviewed. In the mean time, you can try the ad-hoc build in `dist/firefox.zip`. Instructions:

* Unzip the zip file
* about:debugging
* Load Temporary Add-on
* Point to the manifest.json file and click Open
* DONE

**Comment by buunguyen** [comment]
The latest version was approved! Please give it a try.

**Comment by badboy** [comment]
Thanks! Seems to work again.

**Comment by gluons** [comment]
Oh! Thank you very much for informing us. I really appreciate.

**Comment by cmoud94** [comment]
Thanks so much for telling us. I've literally just gave up checking AMO if they already approved new version.
