### ISSUE TITLE
Change project URL to... something else.

### ISSUE THREAD

**Issue by marsjaninzmarsa** [buunguyen/octotree#423]
Since Octotree is no longer Chrome-only extension, more appropriate than [Chrome Web Store](https://chrome.google.com/webstore/detail/octotree/bkhaagjahfmjljalopjnoealnfndnagc?hl=en-US) would be something more browser-agnostic like [addon.com webpage](https://add0n.com/), dedicated GitHub Pages, or even repo itself.

**Comment by buunguyen** [comment]
Chrome web store is still the busiest place, so I'm fine with it for now.
