### ISSUE TITLE
[Firefox] Sidebar width increased when refresh page.

### ISSUE THREAD

**Issue by gluons** [buunguyen/octotree#424]
### Description
I just found that sidebar width in local storage will be increased every time I refresh the webpage.
It may be the cause of #419.

### Environment (if bug)

* **Octotree version:** 2.1.0
* **Browser & version:** Firefox Nightly 57.0a1 (I used to produce it in FF Dev too but I forgot to report 😅)
* **OS & version:** Windows 10 Pro (64 bits)
* **Screenshot, if any (drag an image here)**

![2017-08-11_10-38-42](https://user-images.githubusercontent.com/4688092/29200754-12c6fa4c-7e82-11e7-9971-bca2517e39bf.gif)

**Comment by gluons** [comment]
I've tried 2.2.0 from `dist/firefox.zip` but it still has the same problem.

**Comment by jdreesen** [comment]
I can confirm this issue. It's somewhat annoying to have to pull it back every few page loads.

* Octotree version: 2.1.0 (i'll update this post once 2.2.0 gets approved on AMO)
* Browser & version: FF 55.0.1 (stable)
* OS & version: Windows 10 Pro (64 bits)

**Comment by buunguyen** [comment]
I suppose it has to do with rounding in this line https://github.com/buunguyen/octotree/blob/master/src/octotree.js#L77. Would love a PR.

**Comment by jdreesen** [comment]
The latest version finally got approved on AMO. Sadly the problem still exists.

* Octotree version: 2.3.0
* Browser & version: FF 55.0.3 (stable)
* OS & version: Windows 10 Pro (64 bit)

I've got zero experience with developing browser addons and I don't have much free time to dig into this at the moment which is why I'd be really happy if someone other creates a PR to fix this.

**Comment by buunguyen** [comment]
Fixed in 2.3.1. Will submit to store soon.

**Comment by gluons** [comment]
Thank you. I'll test from this repo first.

**Comment by gluons** [comment]
OK. I've tested with ad-hoc version directly from this repo. It works fine.
Confirm! This issue is actually fixed. 🎉

**Comment by buunguyen** [comment]
Great, thanks for checking!

**Comment by jdreesen** [comment]
Mozilla finally approved the latest version on AMO. The bug is gone now, thx!! <3

**Comment by gluons** [comment]
Thank you very much for informing. 🎉
