### ISSUE TITLE
Firefox supported versions

### ISSUE THREAD

**Issue by pohutukawa** [buunguyen/octotree#426]
### Description
I have wanted to install Octotree on Firefox (54.0, 64 bit, Ubuntu Linux), and it has refused to do so. It seems more recent versions (2.0.20 and 2.1.0) only support Firefox up to the ancient version 43.0.

See: https://addons.mozilla.org/en-US/firefox/addon/octotree/versions/

### Environment (if bug)

* Octotree version: Only half way recent installable version was 2.0.18
* Browser & version: Firefox (54.0, 64 bit)
* OS & version: Ubuntu Linux 17.04 ('zesty')
* Screenshot, if any (drag an image here)

**Comment by naibaf0** [comment]
Interesting. I am running version 2.1.0 in Firefox 55 without issue (marked as legacy though). 

See #422, a new version 2.2.0 that supports Firefox up to 57+ has been pushed to the Mozilla store. They just tend to take their time reviewing. It should be available eventually :)

**Comment by buunguyen** [comment]
I'm not sure what's going on here. Unfortunately, Mozilla is usually slow in approving a version. Maybe you can try an [adhoc release](https://github.com/buunguyen/octotree/releases) to see if an older version would work while waiting for the latest version?

**Comment by pohutukawa** [comment]
The only one that works for me is 2.0.18. Any attempt to use the ones from the `dist/` folder fails with the message "This add-on could not be installed because it appears to be corrupt.". Trying to disable the add-on signing requirements as documented in #220 has no effect, either.
Let's hope that soon a version newer than 2.1.0 will be available from the official Mozilla add-on repos.

**Comment by buunguyen** [comment]
The latest version was approved! Please give it a try.

**Comment by pohutukawa** [comment]
Works well. This issue can be closed.
