### ISSUE TITLE
Doesn't handle folder names contain # correctly

### ISSUE THREAD

**Issue by ferrybig** [buunguyen/octotree#429]
### Description
1. Go to https://github.com/delight-im/ShortURL/blob/master/C%23/ShortURL.cs
2. Observe that inside the url bar, the `#` from the url is urlencoded
3. Open the octotree tree view
4. Open the directory "C#", if not already open
5. Click the file ShortURL.cs
6. Expect Octotree to refresh the page
7. Observe a 404 error instead

### Environment (if bug)

* Octotree version: 2.2.0
* Browser & version: Google Chrome 60.0.3112.101
* OS & version: Windows 10

**Comment by bigredwill** [comment]
This should be fixed as a part of this PR https://github.com/buunguyen/octotree/pull/428
The encoded URL path was not being used

**Comment by buunguyen** [comment]
Released to Chrome store.
