### ISSUE TITLE
Invalid links on directories with a #

### ISSUE THREAD

**Issue by MaitreDede** [buunguyen/octotree#430]
### Description
When browsing a repository with a directory containing a `#` (like in C#), the symbol is not escaped and the links becomes invalid (interpreted as anchor).
Example : https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/bindings/c%23

### Environment (if bug)

* Octotree version: 2.2.0
* Browser & version: Chromium Version 57.0.2987.98 Built on 8.7
* OS & version: Debian 8.9 (64-bit)

**Comment by buunguyen** [comment]
Dup https://github.com/buunguyen/octotree/issues/429
