### ISSUE TITLE
safari 不支持safair 插件的最高级别

### ISSUE THREAD

**Issue by wwwxmu** [buunguyen/octotree#431]
### Description
If this is a bug, provide as much information as you can to help reproduce the issue.
不支持safair 插件的最高级别
### Environment (if bug)

* Octotree version:
* Browser & version: Safari 版本 10.0.3 (12602.4.8)
* OS & version: macOS 10.12.3
* Screenshot, if any (drag an image here)

**Comment by buunguyen** [comment]
Can you post in English please?
