### ISSUE TITLE
Extra junk in Pull Request mode

### ISSUE THREAD

**Issue by kohenkatz** [buunguyen/octotree#434]
### Description
In the new Pull Request viewing mode (which is very nice), the tree has some extra broken elements. At the top of each folder in the tree, there is a folder that says either "# file(s) +## -##" (where "#" is some number). If you expand these folders, they recursively load the same thing over and over again.

### Environment (if bug)

* Octotree version: 2.3.0
* Browser & version: Chrome 61.0.3163.59 (Official Build) beta (64-bit)
* OS & version: Windows 10 Pro x64 v1703 build 15063.540
* Screenshot taken at URL: https://github.com/tymondesigns/jwt-auth/pull/1278

![image](https://user-images.githubusercontent.com/88755/29888069-884ea8b8-8d8d-11e7-8f97-b0ae73cfe8eb.png)

**Comment by buunguyen** [comment]
@bigredwill can you help take a look?

**Comment by bigredwill** [comment]
@kohenkatz The PR you linked to doesn't appear to be the same as the one in the screenshot.  Can you link to a PR that replicates this behavior?

**Comment by bigredwill** [comment]
I found the source of the issue.  When you have `Load entire tree at once === false` and `Show only pull request changes === true`, it causes this recursive folder behavior

**Comment by kohenkatz** [comment]
@bigredwill It is the same PR. The screenshot is with several layers manually expanded.

**Comment by kohenkatz** [comment]
Here is a screenshot with all folders closed - note the top folder in this image is junk.

![image](https://user-images.githubusercontent.com/88755/29888668-ba14f24c-8d8f-11e7-8445-c7864e1fafb8.png)

**Comment by bigredwill** [comment]
@buunguyen @kohenkatz submitted PR to fix this

**Comment by buunguyen** [comment]
Releasing 2.3.1. Thanks @bigredwill!

**Comment by levity** [comment]
The reported behavior is fixed for me, thanks! However what happens now is that when I click on one of the items in the Octotree view, it jumps to the correct file, but then Octotree loads some data (its close button shows a progress spinner), and once it finishes, the page jumps up to the top again.

**Comment by buunguyen** [comment]
It works with my Firefox. Which version of Firefox & Octotree you're using? Does it occur with Chrome? Anything to help debug is useful.

**Comment by levity** [comment]
Hmm -- it was happening with Chrome, but now I can't reproduce it :) Perhaps it was just one tab that had gotten into a strange state.
