### ISSUE TITLE
Backlighting space chars and tab chars

### ISSUE THREAD

**Issue by bopoh13** [buunguyen/octotree#437]
### Wishes
Can you add backlighting of more than 2 spaces and tab chars?

### Description
Sometimes there is confusion when I'm editing someone else's code. The 2 spaces are needed in MarkDown for the carriage return symbol. (I happen to be forgetful) 🍰

**Comment by buunguyen** [comment]
Sorry, I would consider document editing outside the scope of Octotree. I'm in favor of each plugin doing a very specific job and being good at it.

**Comment by bopoh13** [comment]
It's a pity 😿
