### ISSUE TITLE
Tree view for PRs is not working

### ISSUE THREAD

**Issue by momoneko** [buunguyen/octotree#438]
### Description
When opening the view in a PR, instead of showing the tree view, it shows some folders and some files (from the PR). When opening the folders, it goes recursively from the root.

### Environment (if bug)

* Octotree version: 2.3.0
* Browser & version: Firefox 55.0.3 (64-bit)
* OS & version: OS X 10.11.1
* Screenshot: 
https://github.com/ory/hydra/pull/535
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/7412752/30066989-35e6d1b6-9262-11e7-805b-9e15127c6817.png">

**Comment by buunguyen** [comment]
This was fixed in 2.3.1. Please upgrade.

**Comment by jdreesen** [comment]
It seems that 2.3.1 is not yet approved on AMO :(

**Comment by buunguyen** [comment]
Yes, AMO is notoriously slow when coming to reviewing addons.

That bug only happens when "Load entire tree" option is unchecked. For now, you can workaround by make sure that option is selected.
