### ISSUE TITLE
Pressing "s" in a comment box focuses repository search

### ISSUE THREAD

**Issue by mgol** [buunguyen/octotree#440]
### Description
If this is a bug, provide as much information as you can to help reproduce the issue.
1. Open any GitHub issue, e.g. this one.
2. Type "s" in the comment box.
3. Notice the focus has been moved to the repository search and no "s" appeared in the comment box.

This bug makes it impossible to write anything on GitHub; hence it's critical enough I had to disable the extension.

It worked fine so far, I've noticed the issue today.

### Environment (if bug)

* Octotree version:2.3.1
* Browser & version: Chrome 61.0.3163.91
* OS & version: macOS 10.12.6 (16G29)
* Screenshot, if any (drag an image here)

**Comment by buunguyen** [comment]
It seems to work on on my end. Why do you think Octotree causes this problem but not something extension?

**Comment by mgol** [comment]
Hmm, I cannot reproduce it anymore, not sure what changed...

I narrowed it down to Octotree as disabling it made the issue go away (after refreshing a GitHub page) and when I re-enabled it the problem re-appeared. I disabled it and it went back to working correctly.

I guess we can close it now that the issue is gone. Maybe it was interacting with another extension in an unexpected way?

I'll comment here if it happens again.

**Comment by buunguyen** [comment]
Ok, thanks for checking. Octotree does handle shortcut to toggle the tree, default combination is cmd+shift+s. But you would have see the tree toggle instead of focus jumps to search box. So I think the problem is somewhere else. Feel free to reopen if you see it again.
