### ISSUE TITLE
Buttons crush the title

### ISSUE THREAD

**Issue by ue** [buunguyen/octotree#445]
### Description
Setting button and open/close button it`s crush the title

### Environment (if bug)

* Octotree version: 2.3.1
* Browser & version: 61.0.3163.100 latest version
* OS & version:
* Screenshot, if any (drag an image here)

![image](https://user-images.githubusercontent.com/9980498/31266294-c552e930-aa7b-11e7-9469-0e4bb4e48664.png)

**Comment by FlyteWizard** [comment]
Was just going to open an issue for this 👍 

Would be nice to have it not overlap.

**Comment by buunguyen** [comment]
This is no longer an issue.
