### ISSUE TITLE
Long lag when clicking on tree items in Pull Request

### ISSUE THREAD

**Issue by levity** [buunguyen/octotree#450]
### Description

Starting from a Pull Request view, e.g.: https://github.com/buunguyen/octotree/pull/407/files, with Octotree open and files loaded:

If I click on one of those files in the tree, there is a noticeable lag, with a spinner animation in Octotree, before the right file is shown. But these are just anchor links within the current page (e.g. `#diff-1`); all the content is already loaded; so the response should be instant. If I go to the address bar, and manually add or edit the anchor link (to `#diff-12` or `#diff-3`), the browser jumps to the correct part of the page right away, as expected.

The lag is much worse on larger PR's with dozens of file changes.

### Environment

* Octotree version: 2.3.1
* Browser & version: Chrome 61.0.3163.100
* OS & version: macOS Sierra 10.12.6

**Comment by buunguyen** [comment]
Fixed in 2.3.2

**Comment by levity** [comment]
Hurray! Thank you!
