### ISSUE TITLE
README.md support

### ISSUE THREAD

**Issue by panckreous** [buunguyen/octotree#453]
Longer README's are generally much better but also harder to read through - what if it was parsed to display closer to a directory than a single file?

Imagine clicking README.md and instead of taking you to the file like it does with any file it expands and presents the contents as a table of contents? 

Most, if not all, headers have their own hashtag anchors which would allow for direct linking from the sidebar, and the header sizes could be used to define nesting levels

**Comment by buunguyen** [comment]
This is probably out of scope of Octotree.
