### ISSUE TITLE
support multiple tokens/accounts

### ISSUE THREAD

**Issue by mcascone** [buunguyen/octotree#454]
### Description
First off, this is one of the very few extensions that we explicitly recommend installing in my group's development documentation!

#### Feature request:
I have an enterprise GitHub for work, and a personal GitHub.
As far as I can tell the extension only supports a single token, so it will only work for one of the accounts at a time.

I would like to be able to configure the extension with tokens for both (all) of my GitHub accounts, and either switch between them manually or have the extension know which to use based on what URL it's looking at.

### Environment (if bug) N/A

* Octotree version:
* Browser & version: chrome
* OS & version: windows
* Screenshot, if any (drag an image here)

**Comment by mcascone** [comment]
Whoops, looks like this may be a duplicate of #347, unless you disagree.

**Comment by buunguyen** [comment]
Yup, it's duplicated.
