### ISSUE TITLE
Truncate long repo names

### ISSUE THREAD

**Issue by sudhirkhanger** [buunguyen/octotree#459]
### Description
Buttons overlap the repo names that are too long.

### Environment (if bug)

* Octotree version: 2.3.3
* Browser & version:Version 62.0.3202.75 (Official Build) (64-bit)
* OS & version: Linux Fedora 26
* Screenshot, if any (drag an image here)

![screenshot_20171106_215010](https://user-images.githubusercontent.com/841656/32451293-80ed4ae0-c33c-11e7-8e89-388c50404961.png)
![screenshot_20171106_215047](https://user-images.githubusercontent.com/841656/32451332-94d62c3e-c33c-11e7-9c05-625710fc361e.png)

**Comment by jdreesen** [comment]
See #445 #446 #458
