### ISSUE TITLE
Error: Invalid token

### ISSUE THREAD

**Issue by xmlxin** [buunguyen/octotree#460]
My English is not good，This problem is encountered with the plug-in octotree：
Error: Invalid token
The token is invalid. Follow this link to create a new token and paste it below
![image](https://user-images.githubusercontent.com/13414044/32550557-875a2c26-c4c8-11e7-8b8d-c7c262d5d0a7.png)

**Comment by MrZhang123** [comment]
@xmlxin you need cross GFW

**Comment by xmlxin** [comment]
Thanks,I said there was no problem before the big nineteen.

**Comment by buunguyen** [comment]
What is the big nineteen? And are you sure the token is valid? I've seen people copy the extra space after the token string before.

**Comment by xmlxin** [comment]
The nineteen is the meeting of the Communist Party of China. I'm not sure token is valid, because I don't know much about it. however I cross GFW，It's not going to work out
