### ISSUE TITLE
Keep the deepest opened folder fixed to the top of Octotree

### ISSUE THREAD

**Issue by akrawchyk** [buunguyen/octotree#465]
### Feature request

Keep the deepest opened folder fixed to the top of Octotree listing after scrolling past said folder. This is essentially implementing the fixed table header pattern (i.e. http://www.fixedheadertable.com/) within the listing.

Screenshot examples follow.

#### Setup

Navigate to this repository and open Octotree.
Expand a lot of folders, this example has expanded `src > adapters > octicons`.

<img width="195" alt="screen shot 2017-11-22 at 2 51 07 pm" src="https://user-images.githubusercontent.com/903716/33147121-a3200864-cf94-11e7-9d87-7594b1dd9824.png">

If I scroll past the `octicons` folder I lose context for what folder these files are in:

* Current

![screen shot 2017-11-22 at 2 52 20 pm](https://user-images.githubusercontent.com/903716/33147173-d2d40844-cf94-11e7-81b1-b0048f8c89cd.png)

* Desired

![screen shot 2017-11-22 at 2 57 08 pm](https://user-images.githubusercontent.com/903716/33147350-7148749c-cf95-11e7-812c-7eb99a7f2cb3.png)

**Comment by buunguyen** [comment]
Good idea but I don't think jstree (the lib Octotree use to render the tree) supports it. Maybe submitting the issue to jstree itself?

**Comment by akrawchyk** [comment]
I'll look into it, thanks for the feedback @buunguyen. Awesome work on this extension!
