### ISSUE TITLE
Download link does not work on Firefox

### ISSUE THREAD

**Issue by HongxuChen** [buunguyen/octotree#466]
### Description
The download link does not work on firefox, despite it works on my Chrome.

### Environment (if bug)

* Octotree version: 2.3.1
* Browser & version: 57
* OS & version:  Ubuntu 16.04 LTS
* Screenshot, if any (drag an image here): N.A.

**Comment by buunguyen** [comment]
Duplicated https://github.com/buunguyen/octotree/issues/339
