### ISSUE TITLE
Access token is not eeing accept in Firefox 57.0 (64-bit)

### ISSUE THREAD

**Issue by stratosgear** [buunguyen/octotree#468]
### Description
I generate an access token from Github (like I always did while I was using chrome) but the token is rejected by Octotree as:

```
The token is invalid. Follow this link to create a new token and paste it below.
```

### Environment (if bug)

* Octotree version: Latest Firefox extension from https://addons.mozilla.org/en-US/firefox/addon/octotree/ (it says 2.3.1)
* Browser & version: Firefox 57.0 (64-bit)
* OS & version: Arch 4.13.12-1-ARCH #1 SMP PREEMPT Wed Nov 8 11:54:06 CET 2017 x86_64 GNU/Linux
* Screenshot,: 
![screenshot-2017-12-2 buunguyen octotree](https://user-images.githubusercontent.com/193463/33514219-6a546a5c-d750-11e7-8469-31b51d413bb6.png)

**Comment by buunguyen** [comment]
That's strange. Does the same token work in Chrome? Can you check to make sure it doesn't have any trailing space?

**Comment by stratosgear** [comment]
Strange enough the firefox token is NOT working in Chrome.
Chrome's token works in Firefox!
A newly created Github token (done the same way I've been doing it all along) is now working on Firefox.
Mark me confused as hell, and feel free to close the issue.

Apologies for the confusion...
