### ISSUE TITLE
Allow specifying a domain, so that octotree can work with GitHub Enterprise instances

### ISSUE THREAD

**Issue by nnja** [buunguyen/octotree#472]
### Description

GitHub Enterprise is a self-hosted GitHub for companies. More information about it can be found (here)[https://github.com/blog/978-introducing-github-enterprise].

Allow octotree to accept a URL for a GitHub enterprise instance to display the file menu on.

**Comment by buunguyen** [comment]
It supports GHE right now, but you must use Chrome or Opera.
