### ISSUE TITLE
Different file icons for filetypes [Proposal]

### ISSUE THREAD

**Issue by Darkle** [buunguyen/octotree#475]
It'd be cool if you could add an option to have file icons in octotree that represent the different file types, similar to what this browser extension does: https://chrome.google.com/webstore/detail/github-file-icon/ficfmibkjjnpogdcfhfokmihanoldbfe

Screenshot: https://lh3.googleusercontent.com/IjcgKzY-l7gwmtTDYhAjwsRWET1keUktjJcZibmD7D9tCRGBaDg8sJSMfN3InzQONcj3ApWY=w640-h400-e365

**Comment by buunguyen** [comment]
Good idea. Implemented and will release soon.
