### ISSUE TITLE
meson.build icon

### ISSUE THREAD

**Issue by benwaffle** [buunguyen/octotree#479]
meson.build files are used for the [meson](http://mesonbuild.com/) build system

The file is always called `meson.build`. The icon is present in file-icons, at codepoint `\EA54` (see [here](https://github.com/file-icons/source/blob/master/charmap.md))

**Comment by buunguyen** [comment]
Please report the issue here https://github.com/file-icons/atom. Octotree uses this lib to resolve icons.
