### ISSUE TITLE
Why no file download function, some before

### ISSUE THREAD

**Issue by SpiritMan** [buunguyen/octotree#481]
### Description
If this is a bug, provide as much information as you can to help reproduce the issue.

### Environment (if bug)

* Octotree version:2.4.0
* Browser & version: Google Chrome（63.0.3239.132）
* OS & version:10.12.4
* Screenshot, if any (drag an image here)

**Comment by lovebaicai** [comment]
hi，click file icon to download。
like this：
![](http://7xnh53.com1.z0.glb.clouddn.com/20180120144558.png)

**Comment by buunguyen** [comment]
Just fixed the download icon. Will release next week.
