### ISSUE TITLE
Settings icon ui issue

### ISSUE THREAD

**Issue by ShavidzeT** [buunguyen/octotree#483]
### Environment
* Octotree version: 2.4.1
* Browser & version: Google chrome Version 63.0.3239.132 (Official Build) (64-bit)
* OS & version: macOS High Sierra version 10.13.2 (17C205)
* Screenshot:
<img src="https://i.imgur.com/VbS2HtP.png" width="300" />

**Comment by jdreesen** [comment]
See #445 #446 #458 #459
