### ISSUE TITLE
Icon is not correct

### ISSUE THREAD

**Issue by Nbsaw** [buunguyen/octotree#484]
### Description

When i open this [project](https://github.com/QingWei-Li/npmarket/blob/master/src/components/readme-panel.vue#L7),I found this file with a `.vue` extension has an incorrect icon.

### Environment (if bug)

* Octotree version: 2.4.1
* Browser & version:  Chrome 63.0.3239.132
* OS & version: Window 10
* Screenshot below

![image](https://user-images.githubusercontent.com/12481935/35045479-e4d0440c-fbce-11e7-8e6a-ab9f1f4a517d.png)

**Comment by buunguyen** [comment]
Please report issue here https://github.com/file-icons/atom. Octotree uses this lib to resolve icons.
