### ISSUE TITLE
filetype-specific icons don't swap to the "download" icon on hover

### ISSUE THREAD

**Issue by falquaddoomi** [buunguyen/octotree#485]
### Description

If the setting for filetype-specific icons is disabled, hovering over an entry in the treeview causes the generic file icon to swap out for a "download" icon, indicating that if you click the icon itself it will download the file rather than display it in the browser.

When filetype-specific icons are enabled, the icon doesn't change on hover. This has lead to a few accidental downloads when I intended to just display the file.

### Environment (if bug)

* Octotree version: 2.4.1
* Browser & version: Chrome 64.0.3282.99 (Official Build) beta (64-bit)
* OS & version: OS X 10.11.6
* Screenshot, if any (drag an image here)
![screen shot 2018-01-24 at 2 36 42 pm](https://user-images.githubusercontent.com/312923/35334865-0d9d7d2e-0114-11e8-981a-1514622986c0.png)

**Comment by slavikf** [comment]
75

**Comment by buunguyen** [comment]
Fixed 2.4.2.
