### ISSUE TITLE
Deleted my issue contents and title when I accidentally clicked on some link

### ISSUE THREAD

**Issue by evandrocoan** [buunguyen/octotree#487]
Deleted my issue when I accidentally clicked on a link

### Description

This is not simple to reproduce, you have to try multiple times until you got it right. Horribly, it worked right away on the first time I accidentally did it. This is probably related to:

1. https://github.com/buunguyen/octotree/issues/342 Page gets reloaded twice some times

Because the page seemed to reload twice.

1. I was wring a issue on another repository
1. I clicked on some link on the page
1. Then the page changed to that other package
1. Then I hit the back button ![image](https://user-images.githubusercontent.com/5332158/35493352-9e7972c0-0499-11e8-848d-0c76a2bc305c.png), so I do not lose my issue contents and can continue writing it
1. However as soon as the pages loaded back, `octotree` opened its tree and erased forever all my contents, right in front of my eyes, I saw they dying horribly with the octotree page refresh post the page load!

I liked this tools very much, however it is unacceptable to erase my contents. I am mad with all the time I lost recreating everything and I will never be using this tool anymore unless this can be fixed.

### Environment (if bug)

* Octotree version:  2.4.3
* Browser & version: Version 63.0.3239.132 (Official Build) (64-bit)
* OS & version: Microsoft Windows [Version 10.0.15063]
* Screenshot, if any (drag an image here)
    On this recording we can see the contents being erased, however this is not how it happened with me, because on this we cannot see octotree reloading the page. Perhaps it was too fast?
    ![back3](https://user-images.githubusercontent.com/5332158/35493675-4579f412-049c-11e8-8c92-c900463130cf.gif)

**Comment by buunguyen** [comment]
I don't see how this can help. You say it yourself, you accidentally navigated away. Octotree can't help with that.

**Comment by evandrocoan** [comment]
@buunguyen, Google's Chrome restore the page contents, if you hit a link, but octotree, erased the contents after Google Chrome restored them. UNACCEPTABLE!
