### ISSUE TITLE
File icons always same between file and directory [Safari]

### ISSUE THREAD

**Issue by lkebin** [buunguyen/octotree#493]
### Description
File icons always same between file and directory in **Safari**

### Environment (if bug)

* Octotree version: 2.4.3
* Browser & version: Safari 11.0.3
* OS & version: macOS 10.13.3
* Screenshot, if any (drag an image here)

![screen shot 2018-02-12 at 2 16 52 pm](https://user-images.githubusercontent.com/1335935/36085302-cf1ff6e4-0fff-11e8-8588-32259cf5ecb9.png)

**Comment by tbodt** [comment]
#496
