### ISSUE TITLE
Octotree breaks GitHub project page layout

### ISSUE THREAD

**Issue by lleger** [buunguyen/octotree#494]
### Description
Visit any project page on GitHub ([example](https://github.com/gatsbyjs/gatsby/projects/2)) and Octotree breaks the layout by completely covering some of the columns. Ideally, I think, Octotree would be hidden by default on these pages.

Strangely, other full-width pages — like the split diff view on a PR — does *not* break the layout. If Octotree is doing something custom to handle that case, it should probably do the same thing on project pages.

### Environment (if bug)

* Octotree version: 2.0.18
* Browser & version: Safari / Chrome (both exhibit, both latest)
* OS & version: macOS Sierra
* Screenshot, if any (drag an image here)
![screen shot 2018-03-03 at 10 47 26 am](https://user-images.githubusercontent.com/52359/36936870-4b32c7a0-1ed0-11e8-807d-519085127eb3.png)

**Comment by buunguyen** [comment]
Fixed. Gonna release soon. Thanks for reporting!
