### ISSUE TITLE
不小心把右边框拉到最左边拉不回来了怎么办？

### ISSUE THREAD

**Issue by XIURongYao** [buunguyen/octotree#522]
### Description
If this is a bug, provide as much information as you can to help reproduce the issue.

### Environment (if bug)

* Octotree version:
* Browser & version:
* OS & version:
* Screenshot, if any (drag an image here)

**Comment by kkkisme** [comment]
F12->Application->Local Storage->https://github.com->clear all

**Comment by XIURongYao** [comment]
厉害，正常了
