### ISSUE TITLE
Arrow button covers Github logo.

### ISSUE THREAD

**Issue by wassimseif** [buunguyen/octotree#530]
### Description
with the latest GitHub dashboard interface, the octotree toggle button covers GitHub logo on the upper left corner. The button is used to go to the home screen of GitHub
### Environment (if bug)

* Octotree version: latest

* Browser & version: Chrome 68.0.3440.106
* OS & version: Macos 10.13.4
* Screenshot
![screen shot 2018-08-13 at 7 38 31 am](https://user-images.githubusercontent.com/7282773/44013055-e9ed1ea6-9ecb-11e8-8532-ce956e7b0d29.png)

**Comment by wassimseif** [comment]
Weird. for me it pushes the view to the right

![screen shot 2018-09-13 at 1 39 56 pm](https://user-images.githubusercontent.com/7282773/45483769-9506f180-b75a-11e8-9954-f6bfa9413ec8.png)

**Comment by buunguyen** [comment]
Fixed the logo, will release soon.
For the search box, there's a separate ticket here: https://github.com/buunguyen/octotree/issues/537
