### ISSUE TITLE
Crash on Chrome 68.0.3440.106 many times

### ISSUE THREAD

**Issue by chenrui333** [buunguyen/octotree#532]
### Description
If this is a bug, provide as much information as you can to help reproduce the issue.

### Environment (if bug)

* Octotree version: 2.4.6
* Browser & version: Chrome 68.0.3440.106
* OS & version: MacOS Sierra v10.12.6
* Screenshot, if any (drag an image here)
Not application as of now (will attach later)

**Comment by chenrui333** [comment]
Just want to throw out the crash report in here, I can attach some screenshots later.

**Comment by buunguyen** [comment]
Can you open the dev console to see if there's any error?

I'm using exact same Chrome version on OSX Sierra but not seeing the issue.

**Comment by suyanhanx** [comment]
![image](https://user-images.githubusercontent.com/24221472/44693723-57d50b00-aa9c-11e8-8461-1d573389785e.png)
On Windows I only found those errors. My Chrome version is the same. My Windows version is  1803(17134.228). After I stopped the extension , the crash was gone.

**Comment by suyanhanx** [comment]
Maybe some api were wrong ? When using the extension, I even met github's http 500 error.

**Comment by kid1412621** [comment]
crash on Chrome 69 stable version

**Comment by chenrui333** [comment]
Mine got much better after the Mac OS patch update.

**Comment by buunguyen** [comment]
Dup https://github.com/buunguyen/octotree/issues/531
