### ISSUE TITLE
Support option to lazy-load individual folder

### ISSUE THREAD

**Issue by turbohz** [buunguyen/octotree#80]
I'm experiencing UI freeze when browsing this (big) repo:

https://github.com/cdnjs/cdnjs

Seems the tree building somehow locks the DOM.

**Comment by crashbell** [comment]
I just applied lazy load for octotree. Please check it here: https://github.com/crashbell/octotree
I will need to refactor and do some enhancement before making a PR.

**Comment by joedf** [comment]
Very Nice, but i think this would be even better having a check box making it optional :)

**Comment by buunguyen** [comment]
Great job @crashbell! I'd like to see how it performs first. If it's sufficiently fast, then we might not need a checkbox. Let's wait and see. Looking forward to a PR.

**Comment by buunguyen** [comment]
Available in v2 branch and [prebuilt packages](https://github.com/buunguyen/octotree/tree/v2/dist). There's an option to lazy-load folders. Will release v2 to stores next week.
